<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>11 Analysis of variance | A Gentle Introduction to Data Science with R</title>
  <meta name="description" content="11 Analysis of variance | A Gentle Introduction to Data Science with R" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="11 Analysis of variance | A Gentle Introduction to Data Science with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="assets/youreka-logo.png" />
  
  <meta name="github-repo" content="tig3r66/youreka-textbook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="11 Analysis of variance | A Gentle Introduction to Data Science with R" />
  
  
  <meta name="twitter:image" content="assets/youreka-logo.png" />

<meta name="author" content="Eddie Guo" />
<meta name="author" content="Youreka Canada Programs Team" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="basic-statistical-tests.html"/>
<link rel="next" href="linear-regression.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/4.3.1/iframeResizer.min.js">
</script>

<script type="text/javascript">

// Once page is loaded, override and disable popover "scroll into view"
  $(document).ready(function() {
    window.tutorial.scrollIntoView = function() {}
  })

// Add padding to LearnR body when popover shown
  $(document).on("shown.bs.popover", function() {
    var popoverHeight = document.querySelector(".popover").offsetHeight
    document.body.style.paddingTop = popoverHeight + 10 + "px"
  })

// Set padding to 0 when popover hidden
  $(document).on("hide.bs.popover", function() {
    var popoverHeight = document.querySelector(".popover").offsetHeight
    document.body.style.paddingTop = "0px"
  })

</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="assets/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./index.html"><img src="assets/youreka-logo.png" ></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to Youreka Canada</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#how-to-use-this-textbook"><i class="fa fa-check"></i>How to use this textbook</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contributors"><i class="fa fa-check"></i>Contributors</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#credit"><i class="fa fa-check"></i>Credit</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="license.html"><a href="license.html"><i class="fa fa-check"></i>License</a></li>
<li class="part"><span><b>I Prerequisites</b></span></li>
<li class="chapter" data-level="1" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>1</b> Install R and RStudio</a>
<ul>
<li class="chapter" data-level="1.1" data-path="install.html"><a href="install.html#installing-r"><i class="fa fa-check"></i><b>1.1</b> Installing R</a></li>
<li class="chapter" data-level="1.2" data-path="install.html"><a href="install.html#installing-rstudio"><i class="fa fa-check"></i><b>1.2</b> Installing RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="install.html"><a href="install.html#add-on-packages"><i class="fa fa-check"></i><b>1.3</b> Add-on packages</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro-to-r.html"><a href="intro-to-r.html"><i class="fa fa-check"></i><b>2</b> Intro to R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro-to-r.html"><a href="intro-to-r.html#using-interactive-windows"><i class="fa fa-check"></i><b>2.1</b> Using interactive windows</a></li>
<li class="chapter" data-level="2.2" data-path="intro-to-r.html"><a href="intro-to-r.html#objects"><i class="fa fa-check"></i><b>2.2</b> Objects</a></li>
<li class="chapter" data-level="2.3" data-path="intro-to-r.html"><a href="intro-to-r.html#functions"><i class="fa fa-check"></i><b>2.3</b> Functions</a></li>
<li class="chapter" data-level="2.4" data-path="intro-to-r.html"><a href="intro-to-r.html#math-operators"><i class="fa fa-check"></i><b>2.4</b> Math operators</a></li>
<li class="chapter" data-level="2.5" data-path="intro-to-r.html"><a href="intro-to-r.html#conditionals"><i class="fa fa-check"></i><b>2.5</b> Conditionals</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="intro-to-r.html"><a href="intro-to-r.html#if-statements"><i class="fa fa-check"></i><b>2.5.1</b> If statements</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="intro-to-r.html"><a href="intro-to-r.html#working-directory"><i class="fa fa-check"></i><b>2.6</b> Working directory</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="intro-to-r.html"><a href="intro-to-r.html#other-important-things"><i class="fa fa-check"></i><b>2.6.1</b> Other important things</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>3</b> Data structures</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>3.1</b> Vectors</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-structures.html"><a href="data-structures.html#missing-values"><i class="fa fa-check"></i><b>3.1.1</b> Missing values</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-structures.html"><a href="data-structures.html#lists"><i class="fa fa-check"></i><b>3.2</b> Lists</a></li>
<li class="chapter" data-level="3.3" data-path="data-structures.html"><a href="data-structures.html#data-frames"><i class="fa fa-check"></i><b>3.3</b> Data frames</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="data-structures.html"><a href="data-structures.html#external-data"><i class="fa fa-check"></i><b>3.3.1</b> External data</a></li>
<li class="chapter" data-level="3.3.2" data-path="data-structures.html"><a href="data-structures.html#factors"><i class="fa fa-check"></i><b>3.3.2</b> Factors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="loops-and-functions.html"><a href="loops-and-functions.html"><i class="fa fa-check"></i><b>4</b> Loops and functions</a>
<ul>
<li class="chapter" data-level="4.1" data-path="loops-and-functions.html"><a href="loops-and-functions.html#for-loops"><i class="fa fa-check"></i><b>4.1</b> For loops</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="loops-and-functions.html"><a href="loops-and-functions.html#looping-over-multiple-files"><i class="fa fa-check"></i><b>4.1.1</b> Looping over multiple files</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="loops-and-functions.html"><a href="loops-and-functions.html#functions-1"><i class="fa fa-check"></i><b>4.2</b> Functions</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="loops-and-functions.html"><a href="loops-and-functions.html#conditionals-within-functions"><i class="fa fa-check"></i><b>4.2.1</b> Conditionals within functions</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Data Wrangling</b></span></li>
<li class="chapter" data-level="5" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>5</b> Data exploration</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-exploration.html"><a href="data-exploration.html#get-the-gapminder-data"><i class="fa fa-check"></i><b>5.1</b> Get the gapminder data</a></li>
<li class="chapter" data-level="5.2" data-path="data-exploration.html"><a href="data-exploration.html#explore-gapminder"><i class="fa fa-check"></i><b>5.2</b> Explore gapminder</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="data-exploration.html"><a href="data-exploration.html#importing-and-exporting-data"><i class="fa fa-check"></i><b>5.2.1</b> Importing and exporting data</a></li>
<li class="chapter" data-level="5.2.2" data-path="data-exploration.html"><a href="data-exploration.html#exploring-variables-in-a-data-frame"><i class="fa fa-check"></i><b>5.2.2</b> Exploring variables in a data frame</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-exploration.html"><a href="data-exploration.html#data-frames-with-dplyr"><i class="fa fa-check"></i><b>5.3</b> Data frames with dplyr</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="data-exploration.html"><a href="data-exploration.html#subsetting-data"><i class="fa fa-check"></i><b>5.3.1</b> Subsetting data</a></li>
<li class="chapter" data-level="5.3.2" data-path="data-exploration.html"><a href="data-exploration.html#filter-rows-with-filter"><i class="fa fa-check"></i><b>5.3.2</b> Filter rows with <code>filter()</code></a></li>
<li class="chapter" data-level="5.3.3" data-path="data-exploration.html"><a href="data-exploration.html#pipe-operator"><i class="fa fa-check"></i><b>5.3.3</b> Pipe operator <code>%&gt;%</code></a></li>
<li class="chapter" data-level="5.3.4" data-path="data-exploration.html"><a href="data-exploration.html#select-columns-with-select"><i class="fa fa-check"></i><b>5.3.4</b> Select Columns with <code>select()</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="more-dplyr.html"><a href="more-dplyr.html"><i class="fa fa-check"></i><b>6</b> More dplyr</a>
<ul>
<li class="chapter" data-level="6.1" data-path="more-dplyr.html"><a href="more-dplyr.html#review-and-preparation"><i class="fa fa-check"></i><b>6.1</b> Review and preparation</a></li>
<li class="chapter" data-level="6.2" data-path="more-dplyr.html"><a href="more-dplyr.html#use-mutate-to-add-new-variables"><i class="fa fa-check"></i><b>6.2</b> Use mutate() to add new variables</a></li>
<li class="chapter" data-level="6.3" data-path="more-dplyr.html"><a href="more-dplyr.html#use-arrange-to-row-order-data"><i class="fa fa-check"></i><b>6.3</b> Use arrange() to row-order data</a></li>
<li class="chapter" data-level="6.4" data-path="more-dplyr.html"><a href="more-dplyr.html#use-rename-to-rename-variables"><i class="fa fa-check"></i><b>6.4</b> Use rename() to rename variables</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="more-dplyr.html"><a href="more-dplyr.html#use-select-to-rename-and-reposition-variables"><i class="fa fa-check"></i><b>6.4.1</b> Use select() to rename and reposition variables</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="more-dplyr.html"><a href="more-dplyr.html#perform-tasks-on-subsets-with-group_by"><i class="fa fa-check"></i><b>6.5</b> Perform tasks on subsets with <code>group_by()</code></a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="more-dplyr.html"><a href="more-dplyr.html#counting"><i class="fa fa-check"></i><b>6.5.1</b> Counting</a></li>
<li class="chapter" data-level="6.5.2" data-path="more-dplyr.html"><a href="more-dplyr.html#general-summarization"><i class="fa fa-check"></i><b>6.5.2</b> General summarization</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="more-dplyr.html"><a href="more-dplyr.html#comprehensive-practice"><i class="fa fa-check"></i><b>6.6</b> Comprehensive practice</a></li>
<li class="chapter" data-level="6.7" data-path="more-dplyr.html"><a href="more-dplyr.html#data-wrangling-summary"><i class="fa fa-check"></i><b>6.7</b> Data wrangling summary</a></li>
</ul></li>
<li class="part"><span><b>III Statistics</b></span></li>
<li class="chapter" data-level="7" data-path="introduction-to-statistics.html"><a href="introduction-to-statistics.html"><i class="fa fa-check"></i><b>7</b> Introduction to statistics</a>
<ul>
<li class="chapter" data-level="7.1" data-path="introduction-to-statistics.html"><a href="introduction-to-statistics.html#inferential-statistics"><i class="fa fa-check"></i><b>7.1</b> Inferential statistics</a></li>
<li class="chapter" data-level="7.2" data-path="introduction-to-statistics.html"><a href="introduction-to-statistics.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>7.2</b> Measures of central tendency</a></li>
<li class="chapter" data-level="7.3" data-path="introduction-to-statistics.html"><a href="introduction-to-statistics.html#measures-of-spread"><i class="fa fa-check"></i><b>7.3</b> Measures of spread</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html"><i class="fa fa-check"></i><b>8</b> Central limit theorem</a>
<ul>
<li class="chapter" data-level="8.1" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#motivation"><i class="fa fa-check"></i><b>8.1</b> Motivation</a></li>
<li class="chapter" data-level="8.2" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#clt-for-means"><i class="fa fa-check"></i><b>8.2</b> CLT for means</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#clt-part-1"><i class="fa fa-check"></i><b>8.2.1</b> CLT Part 1</a></li>
<li class="chapter" data-level="8.2.2" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#clt-part-2"><i class="fa fa-check"></i><b>8.2.2</b> CLT Part 2</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#clt-for-proportions"><i class="fa fa-check"></i><b>8.3</b> CLT for proportions</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="hypothesis-testing-and-p-values.html"><a href="hypothesis-testing-and-p-values.html"><i class="fa fa-check"></i><b>9</b> Hypothesis testing and p-values</a>
<ul>
<li class="chapter" data-level="9.1" data-path="hypothesis-testing-and-p-values.html"><a href="hypothesis-testing-and-p-values.html#hypothesis-testing"><i class="fa fa-check"></i><b>9.1</b> Hypothesis testing</a></li>
<li class="chapter" data-level="9.2" data-path="hypothesis-testing-and-p-values.html"><a href="hypothesis-testing-and-p-values.html#p-values"><i class="fa fa-check"></i><b>9.2</b> P-values</a></li>
<li class="chapter" data-level="9.3" data-path="hypothesis-testing-and-p-values.html"><a href="hypothesis-testing-and-p-values.html#significance-thresholds"><i class="fa fa-check"></i><b>9.3</b> Significance thresholds</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html"><i class="fa fa-check"></i><b>10</b> Basic statistical tests</a>
<ul>
<li class="chapter" data-level="10.1" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#students-t-test"><i class="fa fa-check"></i><b>10.1</b> Student’s t-test</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#example-1-one-sample-t-test"><i class="fa fa-check"></i><b>10.1.1</b> Example 1: One sample t-test</a></li>
<li class="chapter" data-level="10.1.2" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#example-2-two-sample-t-test"><i class="fa fa-check"></i><b>10.1.2</b> Example 2: Two sample t-test</a></li>
<li class="chapter" data-level="10.1.3" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#example-3-paired-t-test"><i class="fa fa-check"></i><b>10.1.3</b> Example 3: Paired t-test</a></li>
<li class="chapter" data-level="10.1.4" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#t-test-assumptions"><i class="fa fa-check"></i><b>10.1.4</b> T-test Assumptions</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#chi-squared-test"><i class="fa fa-check"></i><b>10.2</b> Chi-squared test</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#chi2-test-for-goodness-of-fit"><i class="fa fa-check"></i><b>10.2.1</b> <span class="math inline">\(\chi^2\)</span> test for goodness-of-fit</a></li>
<li class="chapter" data-level="10.2.2" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#chi2-test-for-independence"><i class="fa fa-check"></i><b>10.2.2</b> <span class="math inline">\(\chi^2\)</span> test for independence</a></li>
<li class="chapter" data-level="10.2.3" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#chi2-test-for-homogeneity"><i class="fa fa-check"></i><b>10.2.3</b> <span class="math inline">\(\chi^2\)</span> test for homogeneity</a></li>
<li class="chapter" data-level="10.2.4" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#chi2-test-assumptions"><i class="fa fa-check"></i><b>10.2.4</b> <span class="math inline">\(\chi^2\)</span> test assumptions</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#additional-resources"><i class="fa fa-check"></i><b>10.3</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>11</b> Analysis of variance</a>
<ul>
<li class="chapter" data-level="11.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#anova-in-a-nutshell"><i class="fa fa-check"></i><b>11.1</b> ANOVA in a nutshell</a></li>
<li class="chapter" data-level="11.2" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#one-way-anova"><i class="fa fa-check"></i><b>11.2</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#the-iris-example"><i class="fa fa-check"></i><b>11.2.1</b> The iris example</a></li>
<li class="chapter" data-level="11.2.2" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#non-parametric-alternatives-to-anova"><i class="fa fa-check"></i><b>11.2.2</b> Non-parametric alternatives to ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#beyond-the-one-way-anova"><i class="fa fa-check"></i><b>11.3</b> Beyond the one-way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>12</b> Linear regression</a>
<ul>
<li class="chapter" data-level="12.1" data-path="linear-regression.html"><a href="linear-regression.html#basic-concepts"><i class="fa fa-check"></i><b>12.1</b> Basic concepts</a></li>
<li class="chapter" data-level="12.2" data-path="linear-regression.html"><a href="linear-regression.html#pearson-correlation"><i class="fa fa-check"></i><b>12.2</b> Pearson correlation</a></li>
<li class="chapter" data-level="12.3" data-path="linear-regression.html"><a href="linear-regression.html#spearman-correlation"><i class="fa fa-check"></i><b>12.3</b> Spearman correlation</a></li>
</ul></li>
<li class="part"><span><b>IV Data Visualization</b></span></li>
<li class="chapter" data-level="13" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html"><i class="fa fa-check"></i><b>13</b> Data visualization basics</a>
<ul>
<li class="chapter" data-level="13.1" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html#a-graphing-template"><i class="fa fa-check"></i><b>13.1</b> A graphing template</a></li>
<li class="chapter" data-level="13.2" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html#scatter-plot"><i class="fa fa-check"></i><b>13.2</b> Scatter plot</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html#trend-lines"><i class="fa fa-check"></i><b>13.2.1</b> Trend lines</a></li>
<li class="chapter" data-level="13.2.2" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html#facets"><i class="fa fa-check"></i><b>13.2.2</b> Facets</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html#aesthetic-mappings"><i class="fa fa-check"></i><b>13.3</b> Aesthetic mappings</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html"><i class="fa fa-check"></i><b>14</b> Getting publication-ready</a>
<ul>
<li class="chapter" data-level="14.1" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#line-plot"><i class="fa fa-check"></i><b>14.1</b> Line plot</a></li>
<li class="chapter" data-level="14.2" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#bar-plot"><i class="fa fa-check"></i><b>14.2</b> Bar plot</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#basics"><i class="fa fa-check"></i><b>14.2.1</b> Basics</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#box-plot"><i class="fa fa-check"></i><b>14.3</b> Box plot</a></li>
<li class="chapter" data-level="14.4" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#histogram-and-density-plot"><i class="fa fa-check"></i><b>14.4</b> Histogram and density plot</a></li>
</ul></li>
<li class="divider"></li>
<li><center>
  <a rel="license" href="./index.html#license">
    License: CC-BY-SA<br>
    <i class = "fab fa-creative-commons fa-2x"></i>
    <i class = "fab fa-creative-commons-by fa-2x"></i>
    <i class = "fab fa-creative-commons-sa fa-2x"></i>
  </a>
</li></center>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Gentle Introduction to Data Science with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="analysis-of-variance" class="section level1" number="11">
<h1><span class="header-section-number">11</span> Analysis of variance</h1>
<p>Throughout this chapter, we will provide a pipeline to help you wrangle data, perform statistical analyses, and (perhaps most importantly) visualize data in R.</p>
<p>Let’s load the usual packages, and one new package called <code>car</code> (Companion to Applied Regression).</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="analysis-of-variance.html#cb275-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gapminder)</span>
<span id="cb275-2"><a href="analysis-of-variance.html#cb275-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb275-3"><a href="analysis-of-variance.html#cb275-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)  <span class="co"># for Levene&#39;s test</span></span></code></pre></div>
<div id="anova-in-a-nutshell" class="section level2" number="11.1">
<h2><span class="header-section-number">11.1</span> ANOVA in a nutshell</h2>
<hr />
<p><strong>Analysis of variance (ANOVA).</strong> ANOVA tells us whether multiple groups are significantly different from each other. We can write our general hypotheses as this:</p>
<ul>
<li>H<span class="math inline">\(_0\)</span>: there is no difference between the groups.</li>
<li>H<span class="math inline">\(_a\)</span>: there is a difference between the groups.</li>
</ul>
<p>Like how the t-test used the t statistic, ANOVA uses the F statistic. In general:</p>
<ul>
<li>A small F means there likely is not a difference between the groups (H0).</li>
<li>A large F means there likely is a difference between the groups (Ha).</li>
</ul>
<p>ANOVA assumes that</p>
<ol style="list-style-type: decimal">
<li>All groups have equal variance, and</li>
<li>All groups have a normal distribution.</li>
</ol>
<hr />
<p>To check the assumptions, first <strong>visualize your data!</strong> This will provide a sanity check for the results from statistical tests. Now for the tests:</p>
<ul>
<li>You can use <code>var.test()</code> or <code>leveneTest()</code> to check for equal variance.</li>
<li>You can use <code>shapiro.test()</code> to check for a normal distribution.</li>
</ul>
<p>An important remark is that ANOVA does not tell you <em>which</em> groups are significantly different, only <em>whether</em> there are significant differences between your groups. Here is a pipeline for running ANOVA:</p>
<ol style="list-style-type: decimal">
<li>Visualize your data. Side-by-side boxplots are a good bet.</li>
<li>Check for equal variance and normality.</li>
<li>Run the ANOVA.
<ul>
<li>If results are not significant, conclude that there there are no significant differences between your groups.</li>
<li>If results are significant, use a <strong>post-hoc test</strong> to see which groups are significantly different (more on this later).</li>
</ul></li>
</ol>
</div>
<div id="one-way-anova" class="section level2" number="11.2">
<h2><span class="header-section-number">11.2</span> One-way ANOVA</h2>
<div id="the-iris-example" class="section level3" number="11.2.1">
<h3><span class="header-section-number">11.2.1</span> The iris example</h3>
<p>The iris dataset contains information about three species of flowers: setosa, veriscolor, and virginia. Iris is a built-in dataset in R, meaning we can call it without reading it in.</p>
<ul>
<li><code>iris$Species</code> refers to one column in <code>iris</code>. That is, the column with the name of the species (setosa, versicolor, or virginica).</li>
<li>We can see how many rows and columns are in a <code>data.frame</code> with the <code>dim</code> command. <code>dim(iris)</code> prints out the number of rows (150) and the number of columns (5):</li>
</ul>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="analysis-of-variance.html#cb276-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris)</span></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
<p>Analysis of Variance (ANOVA) allows us to test whether there are differences in the mean between multiple samples. The question we will address is:</p>
<p><strong>Are there differences in average sepal width among the three species?</strong></p>
<p>As good data scientists, we should first visualize our data.</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="analysis-of-variance.html#cb278-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(iris, <span class="fu">aes</span>(Sepal.Length, <span class="at">col=</span>Species)) <span class="sc">+</span></span>
<span id="cb278-2"><a href="analysis-of-variance.html#cb278-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb278-3"><a href="analysis-of-variance.html#cb278-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/sepal-length-1.png" width="672" /></p>
<p>To run an ANOVA, we need to check if</p>
<ol style="list-style-type: decimal">
<li>The variance is is equal for <em>each group</em>, and</li>
<li>The data distributes normally within <em>each group</em>.</li>
</ol>
<p>Let’s address the first point. Before doing a test, let us look at the figure above. The variance in each group looks relatively equal. Keep this in mind as we interpret Levene’s test for equal variances.</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="analysis-of-variance.html#cb279-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(Sepal.Width <span class="sc">~</span> Species, <span class="at">data =</span> iris)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value Pr(&gt;F)
## group   2  0.5902 0.5555
##       147</code></pre>
<p>What does the p-value suggest?</p>
<button class="collapsible">
Solution
</button>
<div class="collapse_content">
<p>A p-value of 0.5555 suggested that the variances are not significantly different. With this assumption checked, we will proceed with ANOVA. Keep in mind we haven’t yet checked the normality. We will do it after running ANOVA.</p>
</div>
<p><br></p>
<p>We start by building an ANOVA model with the <code>aov()</code> function.</p>
<hr />
<p><strong>ANOVA.</strong> To run ANOVA in R, we need to pass <em>two</em> arguments to the <code>aov()</code> function. In general, this is what an ANOVA call looks like:</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="analysis-of-variance.html#cb281-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(y <span class="sc">~</span> x, data)</span></code></pre></div>
<ol style="list-style-type: decimal">
<li><p>For the <code>formula</code> parameter, the format is <code>y ~ x</code>, where the response variable (y) is to the left of the tilde (~), and the predictor variable (x) is to the right of the tilde.</p></li>
<li><p>For the <code>data</code> parameter, we place the naame of the dataset we want to analyze.</p></li>
</ol>
<hr />
<p>In this example, we are asking if petal length is significantly different among the three species. We also need to tell R where to find the <code>Sepal.Width</code> and <code>Species</code> data, so we pass the variable name of the <code>iris data.frame</code> to the <code>data</code> parameter.</p>
<p>Let’s build the model:</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="analysis-of-variance.html#cb282-1" aria-hidden="true" tabindex="-1"></a>Sepal.Width.aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">formula =</span> Sepal.Width <span class="sc">~</span> Species, <span class="at">data =</span> iris)</span></code></pre></div>
<p>Notice how when we execute this command, nothing printed in the console. This is because we instead sent the output of the <code>aov</code> call to a variable. If you just type the variable name, you will see the familiar output from the <code>aov</code> function:</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="analysis-of-variance.html#cb283-1" aria-hidden="true" tabindex="-1"></a>Sepal.Width.aov</span></code></pre></div>
<pre><code>## Call:
##    aov(formula = Sepal.Width ~ Species, data = iris)
## 
## Terms:
##                  Species Residuals
## Sum of Squares  11.34493  16.96200
## Deg. of Freedom        2       147
## 
## Residual standard error: 0.3396877
## Estimated effects may be unbalanced</code></pre>
<p>To see the results of the ANOVA, we call the <code>summary()</code> function:</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="analysis-of-variance.html#cb285-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Sepal.Width.aov)</span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Species       2  11.35   5.672   49.16 &lt;2e-16 ***
## Residuals   147  16.96   0.115                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>Answer to our question part 1:</strong> The species <em>do</em> have significantly different sepal width (P &lt; 0.001).</p>
<p>However, ANOVA does not tell us <em>which</em> species are different. We can run a <em>post hoc</em> test to assess which species are different. A Tukey test comparing means would be one option. We will run the Tukey test after determining normality.</p>
<button class="collapsible">
Evaluating normality
</button>
<div class="collapse_content">
<p>Now, let’s take a look at the normality. Once again, let’s visualize our data before running a test:</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="analysis-of-variance.html#cb287-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(iris, <span class="fu">aes</span>(Sepal.Length, <span class="at">fill=</span>Species)) <span class="sc">+</span></span>
<span id="cb287-2"><a href="analysis-of-variance.html#cb287-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha=</span><span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb287-3"><a href="analysis-of-variance.html#cb287-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/histo-1.png" width="672" /></p>
<p>From the visualization alone, each species’ distribution of sepal lengths looks normal.</p>
<p>Now, we will plot the diagnostic figures.</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="analysis-of-variance.html#cb288-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Sepal.Width.aov)</span></code></pre></div>
<p><img src="_main_files/figure-html/diagnostics-1.png" width="50%" /><img src="_main_files/figure-html/diagnostics-2.png" width="50%" /><img src="_main_files/figure-html/diagnostics-3.png" width="50%" /><img src="_main_files/figure-html/diagnostics-4.png" width="50%" /></p>
<p>Most importantly, the residuals in Q-Q plot (upper right) should align with the line pretty well. If the residuals were to deviate from the line too much, the data would not be considered normal. If you still perform the ANOVA, you should view your results critically (or ignore them, at worst).</p>
<p>Recall that a residual is an “error” in result. More specifically, a residual is the difference of a given data point from the mean (<span class="math inline">\(x - \mu\)</span>).</p>
<p>Please do not include diagnostic figures in the main text of your manuscripts. This might qualify for a supplementary figure at most.</p>
<p>Although we’ve also examined residuals with the Q-Q plot, we can also use a formal test:</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="analysis-of-variance.html#cb289-1" aria-hidden="true" tabindex="-1"></a>residuals_Sepal_Width <span class="ot">&lt;-</span> <span class="fu">residuals</span>(<span class="at">object =</span> Sepal.Width.aov)</span>
<span id="cb289-2"><a href="analysis-of-variance.html#cb289-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="at">x =</span> residuals_Sepal_Width)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals_Sepal_Width
## W = 0.98948, p-value = 0.323</code></pre>
<p>A p-value of 0.323 suggested that the assumption of normality is reasonable.</p>
</div>
<p><br></p>
<p>So far, we have demonstrated</p>
<ol style="list-style-type: decimal">
<li>Normality in distribution and</li>
<li>Homogeneity in variance.</li>
</ol>
<p>These two justified our choice for one-way ANOVA. The result of ANOVA also indicated that at least one species of the 3 has significantly different sepal width from others. Which ones are significantly different?</p>
<p>To do this, we need to run post-hoc test. Let’s do Tukey Honest Significant Differences (HSD) test. The nice thing is that <code>TukeyHSD()</code> can directly take the result of ANOVA as the argument.</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="analysis-of-variance.html#cb291-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(Sepal.Width.aov)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Sepal.Width ~ Species, data = iris)
## 
## $Species
##                        diff         lwr        upr     p adj
## versicolor-setosa    -0.658 -0.81885528 -0.4971447 0.0000000
## virginica-setosa     -0.454 -0.61485528 -0.2931447 0.0000000
## virginica-versicolor  0.204  0.04314472  0.3648553 0.0087802</code></pre>
<p><strong>Answer to our question part 2:</strong> The difference between every species of flower is significant at <span class="math inline">\(\alpha = 0.05\)</span>.</p>
</div>
<div id="non-parametric-alternatives-to-anova" class="section level3" number="11.2.2">
<h3><span class="header-section-number">11.2.2</span> Non-parametric alternatives to ANOVA</h3>
<p>In reality, your data usually will not fulfill every assumption for an ANOVA.</p>
<p>In case of a non-normal sample, there are two ways to address the problem:</p>
<ol style="list-style-type: decimal">
<li>Apply appropriate <a href="https://fmwww.bc.edu/repec/bocode/t/transint.html">data transformation techniques</a>, or</li>
<li>Use a non-parametric test.</li>
</ol>
<p>I highly recommend you to explore data transformation. If you can rescue your data back to normal distribution, parametric tests usually allow you to do more powerful analysis. If you have exhausted your attempts to data transformation, you may then use non-parametric tests.</p>
<p>When your data doesn’t satisfy the normality or equal variance assumption, ANOVA is not the best test to use. The Kruskal-Wallis test doesn’t assume normality, but it does assume same distribution across groups (equal variance). If your data do not meet either assumption, you would want to use Welch’s one-way test. Now, let’s get back to gapminder data.</p>
<p>First, add another categorical variable calle <code>Income_Level</code>. This time we will split by the quartiles.</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="analysis-of-variance.html#cb293-1" aria-hidden="true" tabindex="-1"></a>dat<span class="fl">.1952</span> <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">1952</span>)</span>
<span id="cb293-2"><a href="analysis-of-variance.html#cb293-2" aria-hidden="true" tabindex="-1"></a>border_1952 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(dat<span class="fl">.1952</span><span class="sc">$</span>gdpPercap, <span class="fu">c</span>(.<span class="dv">25</span>, .<span class="dv">50</span>, .<span class="dv">75</span>))</span>
<span id="cb293-3"><a href="analysis-of-variance.html#cb293-3" aria-hidden="true" tabindex="-1"></a>dat<span class="fl">.1952</span><span class="sc">$</span>Income_Level_1952 <span class="ot">&lt;-</span> <span class="fu">cut</span>(dat<span class="fl">.1952</span><span class="sc">$</span>gdpPercap,</span>
<span id="cb293-4"><a href="analysis-of-variance.html#cb293-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">c</span>(<span class="dv">0</span>, border_1952[<span class="dv">1</span>], border_1952[<span class="dv">2</span>], border_1952[<span class="dv">3</span>], <span class="cn">Inf</span>),</span>
<span id="cb293-5"><a href="analysis-of-variance.html#cb293-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">c</span>(<span class="st">&#39;Low&#39;</span>, <span class="st">&#39;Low Middle&#39;</span>, <span class="st">&#39;High Middle&#39;</span>, <span class="st">&#39;High&#39;</span>))</span>
<span id="cb293-6"><a href="analysis-of-variance.html#cb293-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb293-7"><a href="analysis-of-variance.html#cb293-7" aria-hidden="true" tabindex="-1"></a>dat<span class="fl">.2007</span> <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span> <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2007</span>)</span>
<span id="cb293-8"><a href="analysis-of-variance.html#cb293-8" aria-hidden="true" tabindex="-1"></a>border_2007 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(dat<span class="fl">.2007</span><span class="sc">$</span>gdpPercap, <span class="fu">c</span>(.<span class="dv">25</span>, .<span class="dv">50</span>, .<span class="dv">75</span>))</span>
<span id="cb293-9"><a href="analysis-of-variance.html#cb293-9" aria-hidden="true" tabindex="-1"></a>dat<span class="fl">.2007</span><span class="sc">$</span>Income_Level_2007 <span class="ot">&lt;-</span> <span class="fu">cut</span>(dat<span class="fl">.2007</span><span class="sc">$</span>gdpPercap,</span>
<span id="cb293-10"><a href="analysis-of-variance.html#cb293-10" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">c</span>(<span class="dv">0</span>, border_2007[<span class="dv">1</span>],</span>
<span id="cb293-11"><a href="analysis-of-variance.html#cb293-11" aria-hidden="true" tabindex="-1"></a>                                    border_2007[<span class="dv">2</span>], border_2007[<span class="dv">3</span>], <span class="cn">Inf</span>),</span>
<span id="cb293-12"><a href="analysis-of-variance.html#cb293-12" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">c</span>(<span class="st">&#39;Low&#39;</span>, <span class="st">&#39;Low Middle&#39;</span>, <span class="st">&#39;High Middle&#39;</span>, <span class="st">&#39;High&#39;</span>))</span>
<span id="cb293-13"><a href="analysis-of-variance.html#cb293-13" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat<span class="fl">.1952</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 7
##   country     continent  year lifeExp      pop gdpPercap Income_Level_1952
##   &lt;fct&gt;       &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;    &lt;int&gt;     &lt;dbl&gt; &lt;fct&gt;            
## 1 Afghanistan Asia       1952    28.8  8425333      779. Low              
## 2 Albania     Europe     1952    55.2  1282697     1601. Low Middle       
## 3 Algeria     Africa     1952    43.1  9279525     2449. High Middle      
## 4 Angola      Africa     1952    30.0  4232095     3521. High Middle      
## 5 Argentina   Americas   1952    62.5 17876956     5911. High             
## 6 Australia   Oceania    1952    69.1  8691212    10040. High</code></pre>
<p>For now, let’s focus on the data for the year 1952.</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="analysis-of-variance.html#cb295-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dat<span class="fl">.1952</span>, <span class="fu">aes</span>(<span class="at">x =</span> Income_Level_1952, <span class="at">y =</span> lifeExp)) <span class="sc">+</span></span>
<span id="cb295-2"><a href="analysis-of-variance.html#cb295-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb295-3"><a href="analysis-of-variance.html#cb295-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-128-1.png" width="672" /></p>
<p>Let’s check the variance.</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="analysis-of-variance.html#cb296-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(lifeExp <span class="sc">~</span> Income_Level_1952, <span class="at">data =</span> dat<span class="fl">.1952</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value   Pr(&gt;F)   
## group   3  4.3637 0.005714 **
##       138                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>A p-value of 0.0047 suggested that the variances are significantly different. Therefore, we shoud not run ANOVA or Kruskal-Wallis. Let’s run Welch’s one-way test.</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="analysis-of-variance.html#cb298-1" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">oneway.test</span>(lifeExp <span class="sc">~</span> Income_Level_1952, <span class="at">data =</span> dat<span class="fl">.1952</span>)</span>
<span id="cb298-2"><a href="analysis-of-variance.html#cb298-2" aria-hidden="true" tabindex="-1"></a>result</span></code></pre></div>
<pre><code>## 
##  One-way analysis of means (not assuming equal variances)
## 
## data:  lifeExp and Income_Level_1952
## F = 69.799, num df = 3.000, denom df = 73.647, p-value &lt; 2.2e-16</code></pre>
<p>What does the p-value mean?</p>
<button class="collapsible">
Solution
</button>
<div class="collapse_content">
<p>A p-value of 2.2e-16 suggested that at least one category of <code>Income_Level_1952</code> had values of <code>lifeExp</code> that are significantly different from others. Let’s run a post-hoc test to find out which categories are significant.</p>
</div>
<p><br></p>
<p>Since we are running a non-parametric test, an appropriate test would be Games-Howell post-hoc test. Unfortunately, R does not have a built-in function for Games-Howell. Let’s define a function to do this task.</p>
<button class="collapsible">
Games-Howell test
</button>
<div class="collapse_content">
<p><strong>Note</strong>: you don’t need to know how the code below works.</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="analysis-of-variance.html#cb300-1" aria-hidden="true" tabindex="-1"></a>games.howell <span class="ot">&lt;-</span> <span class="cf">function</span>(grp, obs) {</span>
<span id="cb300-2"><a href="analysis-of-variance.html#cb300-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create combinations</span></span>
<span id="cb300-3"><a href="analysis-of-variance.html#cb300-3" aria-hidden="true" tabindex="-1"></a>  combs <span class="ot">&lt;-</span> <span class="fu">combn</span>(<span class="fu">unique</span>(grp), <span class="dv">2</span>)</span>
<span id="cb300-4"><a href="analysis-of-variance.html#cb300-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb300-5"><a href="analysis-of-variance.html#cb300-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Statistics that will be used throughout the calculations:</span></span>
<span id="cb300-6"><a href="analysis-of-variance.html#cb300-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># n = sample size of each group</span></span>
<span id="cb300-7"><a href="analysis-of-variance.html#cb300-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># groups = number of groups in data</span></span>
<span id="cb300-8"><a href="analysis-of-variance.html#cb300-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Mean = means of each group sample</span></span>
<span id="cb300-9"><a href="analysis-of-variance.html#cb300-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># std = variance of each group sample</span></span>
<span id="cb300-10"><a href="analysis-of-variance.html#cb300-10" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">tapply</span>(obs, grp, length)</span>
<span id="cb300-11"><a href="analysis-of-variance.html#cb300-11" aria-hidden="true" tabindex="-1"></a>  groups <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">tapply</span>(obs, grp, length))</span>
<span id="cb300-12"><a href="analysis-of-variance.html#cb300-12" aria-hidden="true" tabindex="-1"></a>  Mean <span class="ot">&lt;-</span> <span class="fu">tapply</span>(obs, grp, mean)</span>
<span id="cb300-13"><a href="analysis-of-variance.html#cb300-13" aria-hidden="true" tabindex="-1"></a>  std <span class="ot">&lt;-</span> <span class="fu">tapply</span>(obs, grp, var)</span>
<span id="cb300-14"><a href="analysis-of-variance.html#cb300-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb300-15"><a href="analysis-of-variance.html#cb300-15" aria-hidden="true" tabindex="-1"></a>  statistics <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(combs), <span class="cf">function</span>(x) {</span>
<span id="cb300-16"><a href="analysis-of-variance.html#cb300-16" aria-hidden="true" tabindex="-1"></a>    mean.diff <span class="ot">&lt;-</span> Mean[combs[<span class="dv">2</span>,x]] <span class="sc">-</span> Mean[combs[<span class="dv">1</span>,x]]</span>
<span id="cb300-17"><a href="analysis-of-variance.html#cb300-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># t-values</span></span>
<span id="cb300-18"><a href="analysis-of-variance.html#cb300-18" aria-hidden="true" tabindex="-1"></a>    t <span class="ot">&lt;-</span> <span class="fu">abs</span>(Mean[combs[<span class="dv">1</span>,x]] <span class="sc">-</span> Mean[combs[<span class="dv">2</span>,x]]) <span class="sc">/</span> <span class="fu">sqrt</span>((std[combs[<span class="dv">1</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">1</span>,x]]) <span class="sc">+</span> (std[combs[<span class="dv">2</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">2</span>,x]]))</span>
<span id="cb300-19"><a href="analysis-of-variance.html#cb300-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Degrees of Freedom</span></span>
<span id="cb300-20"><a href="analysis-of-variance.html#cb300-20" aria-hidden="true" tabindex="-1"></a>    df <span class="ot">&lt;-</span> (std[combs[<span class="dv">1</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">1</span>,x]] <span class="sc">+</span> std[combs[<span class="dv">2</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">2</span>,x]])<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="co"># numerator dof</span></span>
<span id="cb300-21"><a href="analysis-of-variance.html#cb300-21" aria-hidden="true" tabindex="-1"></a>      ((std[combs[<span class="dv">1</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">1</span>,x]])<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (n[combs[<span class="dv">1</span>,x]] <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># Part 1 of denominator dof</span></span>
<span id="cb300-22"><a href="analysis-of-variance.html#cb300-22" aria-hidden="true" tabindex="-1"></a>         (std[combs[<span class="dv">2</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">2</span>,x]])<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (n[combs[<span class="dv">2</span>,x]] <span class="sc">-</span> <span class="dv">1</span>)) <span class="co"># Part 2 of denominator dof</span></span>
<span id="cb300-23"><a href="analysis-of-variance.html#cb300-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># p-values</span></span>
<span id="cb300-24"><a href="analysis-of-variance.html#cb300-24" aria-hidden="true" tabindex="-1"></a>    p <span class="ot">&lt;-</span> <span class="fu">ptukey</span>(t <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">2</span>), groups, df, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb300-25"><a href="analysis-of-variance.html#cb300-25" aria-hidden="true" tabindex="-1"></a>    <span class="co"># sigma standard error</span></span>
<span id="cb300-26"><a href="analysis-of-variance.html#cb300-26" aria-hidden="true" tabindex="-1"></a>    se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fl">0.5</span> <span class="sc">*</span> (std[combs[<span class="dv">1</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">1</span>,x]] <span class="sc">+</span> std[combs[<span class="dv">2</span>,x]] <span class="sc">/</span> n[combs[<span class="dv">2</span>,x]]))</span>
<span id="cb300-27"><a href="analysis-of-variance.html#cb300-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Upper Confidence Limit</span></span>
<span id="cb300-28"><a href="analysis-of-variance.html#cb300-28" aria-hidden="true" tabindex="-1"></a>    upper.conf <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(combs), <span class="cf">function</span>(x) {</span>
<span id="cb300-29"><a href="analysis-of-variance.html#cb300-29" aria-hidden="true" tabindex="-1"></a>      mean.diff <span class="sc">+</span> <span class="fu">qtukey</span>(<span class="at">p =</span> <span class="fl">0.95</span>, <span class="at">nmeans =</span> groups, <span class="at">df =</span> df) <span class="sc">*</span> se</span>
<span id="cb300-30"><a href="analysis-of-variance.html#cb300-30" aria-hidden="true" tabindex="-1"></a>    })[[<span class="dv">1</span>]]</span>
<span id="cb300-31"><a href="analysis-of-variance.html#cb300-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Lower Confidence Limit</span></span>
<span id="cb300-32"><a href="analysis-of-variance.html#cb300-32" aria-hidden="true" tabindex="-1"></a>    lower.conf <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(combs), <span class="cf">function</span>(x) {</span>
<span id="cb300-33"><a href="analysis-of-variance.html#cb300-33" aria-hidden="true" tabindex="-1"></a>      mean.diff <span class="sc">-</span> <span class="fu">qtukey</span>(<span class="at">p =</span> <span class="fl">0.95</span>, <span class="at">nmeans =</span> groups, <span class="at">df =</span> df) <span class="sc">*</span> se</span>
<span id="cb300-34"><a href="analysis-of-variance.html#cb300-34" aria-hidden="true" tabindex="-1"></a>    })[[<span class="dv">1</span>]]</span>
<span id="cb300-35"><a href="analysis-of-variance.html#cb300-35" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Group Combinations</span></span>
<span id="cb300-36"><a href="analysis-of-variance.html#cb300-36" aria-hidden="true" tabindex="-1"></a>    grp.comb <span class="ot">&lt;-</span> <span class="fu">paste</span>(combs[<span class="dv">1</span>,x], <span class="st">&#39;:&#39;</span>, combs[<span class="dv">2</span>,x])</span>
<span id="cb300-37"><a href="analysis-of-variance.html#cb300-37" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Collect all statistics into list</span></span>
<span id="cb300-38"><a href="analysis-of-variance.html#cb300-38" aria-hidden="true" tabindex="-1"></a>    stats <span class="ot">&lt;-</span> <span class="fu">list</span>(grp.comb, mean.diff, se, t, df, p, upper.conf, lower.conf)</span>
<span id="cb300-39"><a href="analysis-of-variance.html#cb300-39" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb300-40"><a href="analysis-of-variance.html#cb300-40" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb300-41"><a href="analysis-of-variance.html#cb300-41" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Unlist statistics collected earlier</span></span>
<span id="cb300-42"><a href="analysis-of-variance.html#cb300-42" aria-hidden="true" tabindex="-1"></a>  stats.unlisted <span class="ot">&lt;-</span> <span class="fu">lapply</span>(statistics, <span class="cf">function</span>(x) {</span>
<span id="cb300-43"><a href="analysis-of-variance.html#cb300-43" aria-hidden="true" tabindex="-1"></a>    <span class="fu">unlist</span>(x)</span>
<span id="cb300-44"><a href="analysis-of-variance.html#cb300-44" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb300-45"><a href="analysis-of-variance.html#cb300-45" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb300-46"><a href="analysis-of-variance.html#cb300-46" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create dataframe from flattened list</span></span>
<span id="cb300-47"><a href="analysis-of-variance.html#cb300-47" aria-hidden="true" tabindex="-1"></a>  results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">matrix</span>(<span class="fu">unlist</span>(stats.unlisted), <span class="at">nrow =</span> <span class="fu">length</span>(stats.unlisted), <span class="at">byrow=</span><span class="cn">TRUE</span>))</span>
<span id="cb300-48"><a href="analysis-of-variance.html#cb300-48" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Select columns set as factors that should be numeric and change with as.numeric</span></span>
<span id="cb300-49"><a href="analysis-of-variance.html#cb300-49" aria-hidden="true" tabindex="-1"></a>  results[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span><span class="sc">:</span><span class="fu">ncol</span>(results))] <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(<span class="fu">as.matrix</span>(results[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span><span class="sc">:</span><span class="fu">ncol</span>(results))])), <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb300-50"><a href="analysis-of-variance.html#cb300-50" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Rename data frame columns</span></span>
<span id="cb300-51"><a href="analysis-of-variance.html#cb300-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>(results) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;groups&#39;</span>, <span class="st">&#39;Mean Difference&#39;</span>, <span class="st">&#39;Standard Error&#39;</span>, <span class="st">&#39;t&#39;</span>, <span class="st">&#39;df&#39;</span>, <span class="st">&#39;p&#39;</span>, <span class="st">&#39;upper limit&#39;</span>, <span class="st">&#39;lower limit&#39;</span>)</span>
<span id="cb300-52"><a href="analysis-of-variance.html#cb300-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(results)</span>
<span id="cb300-53"><a href="analysis-of-variance.html#cb300-53" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
</div>
<p><br></p>
<p>After defining the function, we can use it. If you decide to use the Games-Howell function, you can simply copy-and-paste it.</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="analysis-of-variance.html#cb301-1" aria-hidden="true" tabindex="-1"></a><span class="fu">games.howell</span>(<span class="at">grp =</span> dat<span class="fl">.1952</span><span class="sc">$</span>Income_Level_1952,  <span class="co"># groups, the categorical variable</span></span>
<span id="cb301-2"><a href="analysis-of-variance.html#cb301-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">obs =</span> dat<span class="fl">.1952</span><span class="sc">$</span>lifeExp)            <span class="co"># observations, the continuous variable</span></span></code></pre></div>
<pre><code>##                     groups Mean Difference Standard Error      t     df     p
## 1         Low : Low Middle           5.569          1.073  3.671 59.455 0.003
## 2        Low : High Middle          13.243          1.287  7.274 51.265 0.000
## 3               Low : High          24.536          1.247 13.917 53.954 0.000
## 4 Low Middle : High Middle           7.673          1.450  3.743 64.272 0.002
## 5        Low Middle : High          18.967          1.414  9.487 66.664 0.000
## 6       High Middle : High          11.294          1.583  5.046 68.787 0.000
##   upper limit lower limit
## 1       9.580       1.559
## 2      18.077       8.408
## 3      29.210      19.863
## 4      13.081       2.266
## 5      24.235      13.699
## 6      17.187       5.401</code></pre>
<p>If you’re interested in learning more, check out <a href="http://www.biostathandbook.com/kruskalwallis.html">this article on the Kruskal-Wallis test</a>.</p>
</div>
</div>
<div id="beyond-the-one-way-anova" class="section level2" number="11.3">
<h2><span class="header-section-number">11.3</span> Beyond the one-way ANOVA</h2>
<p>As seen in the previous example, a one-way ANOVA is a great tool for comparing multiple groups on one categorical variable such as income level. But what if we wanted to examine if life expectancy differs across the years 1952, 1972, and 2007 in addition to income level? In this case, we will need a two-way ANOVA.</p>
<p>Although we won’t cover a two-way ANOVA in this text, you can learn more about it in <a href="http://www.sthda.com/english/wiki/two-way-anova-test-in-r">this article</a>.</p>
<script>
iFrameResize({}, ".interactive");
  
var coll = document.getElementsByClassName("collapsible");
for (var i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.maxHeight){
      content.style.maxHeight = null;
      setTimeout(function() {
        content.style.paddingTop = "0";
        content.style.paddingBottom = "0";
      }, 250)
    } else {
      content.style.paddingTop = "15px";
      content.style.paddingBottom = "10px";
      content.style.maxHeight = content.scrollHeight + "px";
    } 
  });
}
</script>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="basic-statistical-tests.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="linear-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
