<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10 Basic statistical tests | A Gentle Introduction to Data Science with R</title>
  <meta name="description" content="10 Basic statistical tests | A Gentle Introduction to Data Science with R" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="10 Basic statistical tests | A Gentle Introduction to Data Science with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="assets/youreka-logo.png" />
  
  <meta name="github-repo" content="tig3r66/youreka-textbook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10 Basic statistical tests | A Gentle Introduction to Data Science with R" />
  
  
  <meta name="twitter:image" content="assets/youreka-logo.png" />

<meta name="author" content="Eddie Guo" />
<meta name="author" content="Youreka Canada Programs Team" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="hypothesis-testing-and-p-values.html"/>
<link rel="next" href="analysis-of-variance.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/4.3.1/iframeResizer.min.js">
</script>

<script type="text/javascript">

// Once page is loaded, override and disable popover "scroll into view"
  $(document).ready(function() {
    window.tutorial.scrollIntoView = function() {}
  })

// Add padding to LearnR body when popover shown
  $(document).on("shown.bs.popover", function() {
    var popoverHeight = document.querySelector(".popover").offsetHeight
    document.body.style.paddingTop = popoverHeight + 10 + "px"
  })

// Set padding to 0 when popover hidden
  $(document).on("hide.bs.popover", function() {
    var popoverHeight = document.querySelector(".popover").offsetHeight
    document.body.style.paddingTop = "0px"
  })

</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="assets/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./index.html"><img src="assets/youreka-logo.png" ></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to Youreka Canada</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#how-to-use-this-textbook"><i class="fa fa-check"></i>How to use this textbook</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contributors"><i class="fa fa-check"></i>Contributors</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#credit"><i class="fa fa-check"></i>Credit</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="license.html"><a href="license.html"><i class="fa fa-check"></i>License</a></li>
<li class="part"><span><b>I Prerequisites</b></span></li>
<li class="chapter" data-level="1" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>1</b> Install R and RStudio</a>
<ul>
<li class="chapter" data-level="1.1" data-path="install.html"><a href="install.html#installing-r"><i class="fa fa-check"></i><b>1.1</b> Installing R</a></li>
<li class="chapter" data-level="1.2" data-path="install.html"><a href="install.html#installing-rstudio"><i class="fa fa-check"></i><b>1.2</b> Installing RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="install.html"><a href="install.html#add-on-packages"><i class="fa fa-check"></i><b>1.3</b> Add-on packages</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro-to-r.html"><a href="intro-to-r.html"><i class="fa fa-check"></i><b>2</b> Intro to R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro-to-r.html"><a href="intro-to-r.html#using-interactive-windows"><i class="fa fa-check"></i><b>2.1</b> Using interactive windows</a></li>
<li class="chapter" data-level="2.2" data-path="intro-to-r.html"><a href="intro-to-r.html#objects"><i class="fa fa-check"></i><b>2.2</b> Objects</a></li>
<li class="chapter" data-level="2.3" data-path="intro-to-r.html"><a href="intro-to-r.html#functions"><i class="fa fa-check"></i><b>2.3</b> Functions</a></li>
<li class="chapter" data-level="2.4" data-path="intro-to-r.html"><a href="intro-to-r.html#math-operators"><i class="fa fa-check"></i><b>2.4</b> Math operators</a></li>
<li class="chapter" data-level="2.5" data-path="intro-to-r.html"><a href="intro-to-r.html#conditionals"><i class="fa fa-check"></i><b>2.5</b> Conditionals</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="intro-to-r.html"><a href="intro-to-r.html#if-statements"><i class="fa fa-check"></i><b>2.5.1</b> If statements</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="intro-to-r.html"><a href="intro-to-r.html#working-directory"><i class="fa fa-check"></i><b>2.6</b> Working directory</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="intro-to-r.html"><a href="intro-to-r.html#other-important-things"><i class="fa fa-check"></i><b>2.6.1</b> Other important things</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>3</b> Data structures</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>3.1</b> Vectors</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-structures.html"><a href="data-structures.html#missing-values"><i class="fa fa-check"></i><b>3.1.1</b> Missing values</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-structures.html"><a href="data-structures.html#lists"><i class="fa fa-check"></i><b>3.2</b> Lists</a></li>
<li class="chapter" data-level="3.3" data-path="data-structures.html"><a href="data-structures.html#data-frames"><i class="fa fa-check"></i><b>3.3</b> Data frames</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="data-structures.html"><a href="data-structures.html#external-data"><i class="fa fa-check"></i><b>3.3.1</b> External data</a></li>
<li class="chapter" data-level="3.3.2" data-path="data-structures.html"><a href="data-structures.html#factors"><i class="fa fa-check"></i><b>3.3.2</b> Factors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="loops-and-functions.html"><a href="loops-and-functions.html"><i class="fa fa-check"></i><b>4</b> Loops and functions</a>
<ul>
<li class="chapter" data-level="4.1" data-path="loops-and-functions.html"><a href="loops-and-functions.html#for-loops"><i class="fa fa-check"></i><b>4.1</b> For loops</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="loops-and-functions.html"><a href="loops-and-functions.html#looping-over-multiple-files"><i class="fa fa-check"></i><b>4.1.1</b> Looping over multiple files</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="loops-and-functions.html"><a href="loops-and-functions.html#functions-1"><i class="fa fa-check"></i><b>4.2</b> Functions</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="loops-and-functions.html"><a href="loops-and-functions.html#conditionals-within-functions"><i class="fa fa-check"></i><b>4.2.1</b> Conditionals within functions</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Data Wrangling</b></span></li>
<li class="chapter" data-level="5" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>5</b> Data exploration</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-exploration.html"><a href="data-exploration.html#get-the-gapminder-data"><i class="fa fa-check"></i><b>5.1</b> Get the gapminder data</a></li>
<li class="chapter" data-level="5.2" data-path="data-exploration.html"><a href="data-exploration.html#explore-gapminder"><i class="fa fa-check"></i><b>5.2</b> Explore gapminder</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="data-exploration.html"><a href="data-exploration.html#importing-and-exporting-data"><i class="fa fa-check"></i><b>5.2.1</b> Importing and exporting data</a></li>
<li class="chapter" data-level="5.2.2" data-path="data-exploration.html"><a href="data-exploration.html#exploring-variables-in-a-data-frame"><i class="fa fa-check"></i><b>5.2.2</b> Exploring variables in a data frame</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-exploration.html"><a href="data-exploration.html#data-frames-with-dplyr"><i class="fa fa-check"></i><b>5.3</b> Data frames with dplyr</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="data-exploration.html"><a href="data-exploration.html#subsetting-data"><i class="fa fa-check"></i><b>5.3.1</b> Subsetting data</a></li>
<li class="chapter" data-level="5.3.2" data-path="data-exploration.html"><a href="data-exploration.html#filter-rows-with-filter"><i class="fa fa-check"></i><b>5.3.2</b> Filter rows with <code>filter()</code></a></li>
<li class="chapter" data-level="5.3.3" data-path="data-exploration.html"><a href="data-exploration.html#pipe-operator"><i class="fa fa-check"></i><b>5.3.3</b> Pipe operator <code>%&gt;%</code></a></li>
<li class="chapter" data-level="5.3.4" data-path="data-exploration.html"><a href="data-exploration.html#select-columns-with-select"><i class="fa fa-check"></i><b>5.3.4</b> Select Columns with <code>select()</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="more-dplyr.html"><a href="more-dplyr.html"><i class="fa fa-check"></i><b>6</b> More dplyr</a>
<ul>
<li class="chapter" data-level="6.1" data-path="more-dplyr.html"><a href="more-dplyr.html#review-and-preparation"><i class="fa fa-check"></i><b>6.1</b> Review and preparation</a></li>
<li class="chapter" data-level="6.2" data-path="more-dplyr.html"><a href="more-dplyr.html#use-mutate-to-add-new-variables"><i class="fa fa-check"></i><b>6.2</b> Use mutate() to add new variables</a></li>
<li class="chapter" data-level="6.3" data-path="more-dplyr.html"><a href="more-dplyr.html#use-arrange-to-row-order-data"><i class="fa fa-check"></i><b>6.3</b> Use arrange() to row-order data</a></li>
<li class="chapter" data-level="6.4" data-path="more-dplyr.html"><a href="more-dplyr.html#use-rename-to-rename-variables"><i class="fa fa-check"></i><b>6.4</b> Use rename() to rename variables</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="more-dplyr.html"><a href="more-dplyr.html#use-select-to-rename-and-reposition-variables"><i class="fa fa-check"></i><b>6.4.1</b> Use select() to rename and reposition variables</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="more-dplyr.html"><a href="more-dplyr.html#perform-tasks-on-subsets-with-group_by"><i class="fa fa-check"></i><b>6.5</b> Perform tasks on subsets with <code>group_by()</code></a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="more-dplyr.html"><a href="more-dplyr.html#counting"><i class="fa fa-check"></i><b>6.5.1</b> Counting</a></li>
<li class="chapter" data-level="6.5.2" data-path="more-dplyr.html"><a href="more-dplyr.html#general-summarization"><i class="fa fa-check"></i><b>6.5.2</b> General summarization</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="more-dplyr.html"><a href="more-dplyr.html#comprehensive-practice"><i class="fa fa-check"></i><b>6.6</b> Comprehensive practice</a></li>
<li class="chapter" data-level="6.7" data-path="more-dplyr.html"><a href="more-dplyr.html#data-wrangling-summary"><i class="fa fa-check"></i><b>6.7</b> Data wrangling summary</a></li>
</ul></li>
<li class="part"><span><b>III Statistics</b></span></li>
<li class="chapter" data-level="7" data-path="introduction-to-statistics.html"><a href="introduction-to-statistics.html"><i class="fa fa-check"></i><b>7</b> Introduction to statistics</a>
<ul>
<li class="chapter" data-level="7.1" data-path="introduction-to-statistics.html"><a href="introduction-to-statistics.html#inferential-statistics"><i class="fa fa-check"></i><b>7.1</b> Inferential statistics</a></li>
<li class="chapter" data-level="7.2" data-path="introduction-to-statistics.html"><a href="introduction-to-statistics.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>7.2</b> Measures of central tendency</a></li>
<li class="chapter" data-level="7.3" data-path="introduction-to-statistics.html"><a href="introduction-to-statistics.html#measures-of-spread"><i class="fa fa-check"></i><b>7.3</b> Measures of spread</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html"><i class="fa fa-check"></i><b>8</b> Central limit theorem</a>
<ul>
<li class="chapter" data-level="8.1" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#motivation"><i class="fa fa-check"></i><b>8.1</b> Motivation</a></li>
<li class="chapter" data-level="8.2" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#clt-for-means"><i class="fa fa-check"></i><b>8.2</b> CLT for means</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#clt-part-1"><i class="fa fa-check"></i><b>8.2.1</b> CLT Part 1</a></li>
<li class="chapter" data-level="8.2.2" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#clt-part-2"><i class="fa fa-check"></i><b>8.2.2</b> CLT Part 2</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#clt-for-proportions"><i class="fa fa-check"></i><b>8.3</b> CLT for proportions</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="hypothesis-testing-and-p-values.html"><a href="hypothesis-testing-and-p-values.html"><i class="fa fa-check"></i><b>9</b> Hypothesis testing and p-values</a>
<ul>
<li class="chapter" data-level="9.1" data-path="hypothesis-testing-and-p-values.html"><a href="hypothesis-testing-and-p-values.html#hypothesis-testing"><i class="fa fa-check"></i><b>9.1</b> Hypothesis testing</a></li>
<li class="chapter" data-level="9.2" data-path="hypothesis-testing-and-p-values.html"><a href="hypothesis-testing-and-p-values.html#p-values"><i class="fa fa-check"></i><b>9.2</b> P-values</a></li>
<li class="chapter" data-level="9.3" data-path="hypothesis-testing-and-p-values.html"><a href="hypothesis-testing-and-p-values.html#significance-thresholds"><i class="fa fa-check"></i><b>9.3</b> Significance thresholds</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html"><i class="fa fa-check"></i><b>10</b> Basic statistical tests</a>
<ul>
<li class="chapter" data-level="10.1" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#students-t-test"><i class="fa fa-check"></i><b>10.1</b> Student’s t-test</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#example-1-one-sample-t-test"><i class="fa fa-check"></i><b>10.1.1</b> Example 1: One sample t-test</a></li>
<li class="chapter" data-level="10.1.2" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#example-2-two-sample-t-test"><i class="fa fa-check"></i><b>10.1.2</b> Example 2: Two sample t-test</a></li>
<li class="chapter" data-level="10.1.3" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#example-3-paired-t-test"><i class="fa fa-check"></i><b>10.1.3</b> Example 3: Paired t-test</a></li>
<li class="chapter" data-level="10.1.4" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#t-test-assumptions"><i class="fa fa-check"></i><b>10.1.4</b> T-test Assumptions</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#chi-squared-test"><i class="fa fa-check"></i><b>10.2</b> Chi-squared test</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#chi2-test-for-goodness-of-fit"><i class="fa fa-check"></i><b>10.2.1</b> <span class="math inline">\(\chi^2\)</span> test for goodness-of-fit</a></li>
<li class="chapter" data-level="10.2.2" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#chi2-test-for-independence"><i class="fa fa-check"></i><b>10.2.2</b> <span class="math inline">\(\chi^2\)</span> test for independence</a></li>
<li class="chapter" data-level="10.2.3" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#chi2-test-for-homogeneity"><i class="fa fa-check"></i><b>10.2.3</b> <span class="math inline">\(\chi^2\)</span> test for homogeneity</a></li>
<li class="chapter" data-level="10.2.4" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#chi2-test-assumptions"><i class="fa fa-check"></i><b>10.2.4</b> <span class="math inline">\(\chi^2\)</span> test assumptions</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="basic-statistical-tests.html"><a href="basic-statistical-tests.html#additional-resources"><i class="fa fa-check"></i><b>10.3</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>11</b> Analysis of variance</a>
<ul>
<li class="chapter" data-level="11.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#anova-in-a-nutshell"><i class="fa fa-check"></i><b>11.1</b> ANOVA in a nutshell</a></li>
<li class="chapter" data-level="11.2" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#one-way-anova"><i class="fa fa-check"></i><b>11.2</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#the-iris-example"><i class="fa fa-check"></i><b>11.2.1</b> The iris example</a></li>
<li class="chapter" data-level="11.2.2" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#non-parametric-alternatives-to-anova"><i class="fa fa-check"></i><b>11.2.2</b> Non-parametric alternatives to ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#beyond-the-one-way-anova"><i class="fa fa-check"></i><b>11.3</b> Beyond the one-way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>12</b> Linear regression</a>
<ul>
<li class="chapter" data-level="12.1" data-path="linear-regression.html"><a href="linear-regression.html#basic-concepts"><i class="fa fa-check"></i><b>12.1</b> Basic concepts</a></li>
<li class="chapter" data-level="12.2" data-path="linear-regression.html"><a href="linear-regression.html#pearson-correlation"><i class="fa fa-check"></i><b>12.2</b> Pearson correlation</a></li>
<li class="chapter" data-level="12.3" data-path="linear-regression.html"><a href="linear-regression.html#spearman-correlation"><i class="fa fa-check"></i><b>12.3</b> Spearman correlation</a></li>
</ul></li>
<li class="part"><span><b>IV Data Visualization</b></span></li>
<li class="chapter" data-level="13" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html"><i class="fa fa-check"></i><b>13</b> Data visualization basics</a>
<ul>
<li class="chapter" data-level="13.1" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html#a-graphing-template"><i class="fa fa-check"></i><b>13.1</b> A graphing template</a></li>
<li class="chapter" data-level="13.2" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html#scatter-plot"><i class="fa fa-check"></i><b>13.2</b> Scatter plot</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html#trend-lines"><i class="fa fa-check"></i><b>13.2.1</b> Trend lines</a></li>
<li class="chapter" data-level="13.2.2" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html#facets"><i class="fa fa-check"></i><b>13.2.2</b> Facets</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="data-visualization-basics.html"><a href="data-visualization-basics.html#aesthetic-mappings"><i class="fa fa-check"></i><b>13.3</b> Aesthetic mappings</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html"><i class="fa fa-check"></i><b>14</b> Getting publication-ready</a>
<ul>
<li class="chapter" data-level="14.1" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#line-plot"><i class="fa fa-check"></i><b>14.1</b> Line plot</a></li>
<li class="chapter" data-level="14.2" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#bar-plot"><i class="fa fa-check"></i><b>14.2</b> Bar plot</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#basics"><i class="fa fa-check"></i><b>14.2.1</b> Basics</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#box-plot"><i class="fa fa-check"></i><b>14.3</b> Box plot</a></li>
<li class="chapter" data-level="14.4" data-path="getting-publication-ready.html"><a href="getting-publication-ready.html#histogram-and-density-plot"><i class="fa fa-check"></i><b>14.4</b> Histogram and density plot</a></li>
</ul></li>
<li class="divider"></li>
<li><center>
  <a rel="license" href="./index.html#license">
    License: CC-BY-SA<br>
    <i class = "fab fa-creative-commons fa-2x"></i>
    <i class = "fab fa-creative-commons-by fa-2x"></i>
    <i class = "fab fa-creative-commons-sa fa-2x"></i>
  </a>
</li></center>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Gentle Introduction to Data Science with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="basic-statistical-tests" class="section level1" number="10">
<h1><span class="header-section-number">10</span> Basic statistical tests</h1>
<p>R contains extremely powerful tools for data science. These tools are either built-in or available from packages. Thoughout this section we hope to demonstrate best practices organizing, analyzing, and visualizing data in R.</p>
<p>We will again work with the gapminder dataset. Let’s load the usual packages.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="basic-statistical-tests.html#cb199-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gapminder)</span>
<span id="cb199-2"><a href="basic-statistical-tests.html#cb199-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<p>When you get a new dataset, your first instinct as a good data scientist should be to explore it.</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="basic-statistical-tests.html#cb200-1" aria-hidden="true" tabindex="-1"></a>gapminder  <span class="co"># also recall str(), head(), names()</span></span></code></pre></div>
<pre><code>## # A tibble: 1,704 x 6
##    country     continent  year lifeExp      pop gdpPercap
##    &lt;fct&gt;       &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;    &lt;int&gt;     &lt;dbl&gt;
##  1 Afghanistan Asia       1952    28.8  8425333      779.
##  2 Afghanistan Asia       1957    30.3  9240934      821.
##  3 Afghanistan Asia       1962    32.0 10267083      853.
##  4 Afghanistan Asia       1967    34.0 11537966      836.
##  5 Afghanistan Asia       1972    36.1 13079460      740.
##  6 Afghanistan Asia       1977    38.4 14880372      786.
##  7 Afghanistan Asia       1982    39.9 12881816      978.
##  8 Afghanistan Asia       1987    40.8 13867957      852.
##  9 Afghanistan Asia       1992    41.7 16317921      649.
## 10 Afghanistan Asia       1997    41.8 22227415      635.
## # … with 1,694 more rows</code></pre>
<p>Note the variables <code>country</code> and <code>continent</code> are considered factors (<code>fct</code>), which is a catagorical data. We can use <code>levels()</code> to observe the catagories within a factor column.</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="basic-statistical-tests.html#cb202-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(gapminder<span class="sc">$</span>continent)</span></code></pre></div>
<pre><code>## [1] &quot;Africa&quot;   &quot;Americas&quot; &quot;Asia&quot;     &quot;Europe&quot;   &quot;Oceania&quot;</code></pre>
<div id="students-t-test" class="section level2" number="10.1">
<h2><span class="header-section-number">10.1</span> Student’s t-test</h2>
<hr />
<p><strong>Student’s t-test.</strong> A t-test is used to determine if there is a significant difference between the means of two groups.</p>
<hr />
<p>We use t-tests to compare means between two samples:</p>
<p>Given two sample means ̄y0, ̄y1:</p>
<p><strong>Null hypothesis (H0):</strong> sample means are equal OR the difference between sample
means is equal to some value d0 (i.e., ̄y0 - ̄y1 = d0).</p>
<p><strong>Alternative hypothesis (Ha):</strong> sample means are not equal OR the difference between
sample means is not equal to some value d0.
There are four main “flavours” to the t-test (one-sample, equal variance, unequal
variance, pooled).</p>
<p>Let’s start by asking the mean life expectancy of the continents in 1952. First, we’ll summarize our data.</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="basic-statistical-tests.html#cb204-1" aria-hidden="true" tabindex="-1"></a>gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb204-2"><a href="basic-statistical-tests.html#cb204-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">1952</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb204-3"><a href="basic-statistical-tests.html#cb204-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(continent) <span class="sc">%&gt;%</span></span>
<span id="cb204-4"><a href="basic-statistical-tests.html#cb204-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">mean</span>(lifeExp))</span></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##   continent `mean(lifeExp)`
##   &lt;fct&gt;               &lt;dbl&gt;
## 1 Africa               39.1
## 2 Americas             53.3
## 3 Asia                 46.3
## 4 Europe               64.4
## 5 Oceania              69.3</code></pre>
<p>The life expectancy of Europe is about 64.4 years. It seems close to 65, the standard age often associated with retirement in Canada (and when full pension benefits become available!). Is this life expectancy significantly different from 65 years?</p>
<div id="example-1-one-sample-t-test" class="section level3" number="10.1.1">
<h3><span class="header-section-number">10.1.1</span> Example 1: One sample t-test</h3>
<p>To answer this question, we can use a one sample t-test. We will test the sample (life expectancy measured in Europe in 1952) to see if there is a significant difference between the life expectancy in Europe (64.4 years) and 65 years. Can you set up the appropriate hypotheses to test?</p>
<button class="collapsible">
Solution
</button>
<div class="collapse_content">
<p>Let <span class="math inline">\(\mu\)</span> be the average life expectancy of people in Europe in 1952. Then,</p>
<ul>
<li>H<span class="math inline">\(_0: \mu = 65\)</span></li>
<li>H<span class="math inline">\(_a: \mu \neq 65\)</span></li>
</ul>
</div>
<p><br></p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="basic-statistical-tests.html#cb206-1" aria-hidden="true" tabindex="-1"></a>Euro.life<span class="fl">.1952</span> <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span></span>
<span id="cb206-2"><a href="basic-statistical-tests.html#cb206-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(continent <span class="sc">==</span> <span class="st">&#39;Europe&#39;</span>, year <span class="sc">==</span> <span class="dv">1952</span>) <span class="sc">%&gt;%</span></span>
<span id="cb206-3"><a href="basic-statistical-tests.html#cb206-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(lifeExp)</span>
<span id="cb206-4"><a href="basic-statistical-tests.html#cb206-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Euro.life<span class="fl">.1952</span>, <span class="at">mu =</span> <span class="dv">65</span>, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  Euro.life.1952
## t = -0.50931, df = 29, p-value = 0.6144
## alternative hypothesis: true mean is not equal to 65
## 95 percent confidence interval:
##  62.03323 66.78377
## sample estimates:
## mean of x 
##   64.4085</code></pre>
<p>Notice that p-value is 0.6144. Usually, we choose the significance threshold (<span class="math inline">\(\alpha\)</span>) to be 0.05. Since p &lt; <span class="math inline">\(\alpha\)</span>, we conclude that the life expectancy of Europeans in 1952 doesn’t give us evidence indicating a difference in life expectancy from 65.</p>
<p>We can also plot this:</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="basic-statistical-tests.html#cb208-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb208-2"><a href="basic-statistical-tests.html#cb208-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(Euro.life<span class="fl">.1952</span><span class="sc">$</span>lifeExp), <span class="at">bins=</span><span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb208-3"><a href="basic-statistical-tests.html#cb208-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">65</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb208-4"><a href="basic-statistical-tests.html#cb208-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;European life expectancy in 1952 (years)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Count&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<p><strong>Note:</strong> This is NOT a figure you would include in an academic paper as the quality is quite low. We’re visualizing this just so we have a better idea of what’s going on with the data.</p>
<button class="collapsible">
Wilcoxon signed-rank test
</button>
<div class="collapse_content">
<p>The non-parametric test equivalent to one sample t-test is Wilcoxon signed-rank test.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="basic-statistical-tests.html#cb209-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(Euro.life<span class="fl">.1952</span><span class="sc">$</span>lifeExp, <span class="at">mu=</span><span class="dv">65</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank exact test
## 
## data:  Euro.life.1952$lifeExp
## V = 238, p-value = 0.9193
## alternative hypothesis: true location is not equal to 65</code></pre>
<p>The non-parametric test gave us the same conclusion.</p>
<p><strong>CAUTION:</strong> Although we obtained the same results with both the parametric t-test and non-parametric signed-rank test, their use cases are VERY different. We prefer to use parametric tests because they give us more statistical power. Only use non-parametric tests with sample sizes less than 30 and if the data is not normally distributed.</p>
</div>
</div>
<div id="example-2-two-sample-t-test" class="section level3" number="10.1.2">
<h3><span class="header-section-number">10.1.2</span> Example 2: Two sample t-test</h3>
<p>Does Asia and Africa differ in life expectancy in 1952? To compare two groups of data, we need a two sample t-test. Can you set up the hypotheses?</p>
<button class="collapsible">
Solution
</button>
<div class="collapse_content">
<p>Let <span class="math inline">\(\mu_1\)</span> be the average life expectancy of people in Asia in 1952. Let <span class="math inline">\(\mu_2\)</span> be the average life expectancy of people in Africa in 1952. Then,</p>
<ul>
<li>H<span class="math inline">\(_0: \mu_1 - \mu_2 = 0\)</span></li>
<li>H<span class="math inline">\(_a: \mu_1 - \mu_2 \neq 0\)</span></li>
</ul>
</div>
<p><br></p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="basic-statistical-tests.html#cb211-1" aria-hidden="true" tabindex="-1"></a>As.Af <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb211-2"><a href="basic-statistical-tests.html#cb211-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">1952</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb211-3"><a href="basic-statistical-tests.html#cb211-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(continent <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Africa&quot;</span>, <span class="st">&quot;Asia&quot;</span>))</span>
<span id="cb211-4"><a href="basic-statistical-tests.html#cb211-4" aria-hidden="true" tabindex="-1"></a>As.Af</span></code></pre></div>
<pre><code>## # A tibble: 85 x 6
##    country      continent  year lifeExp      pop gdpPercap
##    &lt;fct&gt;        &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;    &lt;int&gt;     &lt;dbl&gt;
##  1 Afghanistan  Asia       1952    28.8  8425333      779.
##  2 Algeria      Africa     1952    43.1  9279525     2449.
##  3 Angola       Africa     1952    30.0  4232095     3521.
##  4 Bahrain      Asia       1952    50.9   120447     9867.
##  5 Bangladesh   Asia       1952    37.5 46886859      684.
##  6 Benin        Africa     1952    38.2  1738315     1063.
##  7 Botswana     Africa     1952    47.6   442308      851.
##  8 Burkina Faso Africa     1952    32.0  4469979      543.
##  9 Burundi      Africa     1952    39.0  2445618      339.
## 10 Cambodia     Asia       1952    39.4  4693836      368.
## # … with 75 more rows</code></pre>
<p>We can plot this:</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="basic-statistical-tests.html#cb213-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(As.Af, <span class="fu">aes</span>(continent, lifeExp)) <span class="sc">+</span></span>
<span id="cb213-2"><a href="basic-statistical-tests.html#cb213-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_dotplot</span>(<span class="at">binaxis =</span> <span class="st">&#39;y&#39;</span>, <span class="at">stackdir =</span> <span class="st">&#39;center&#39;</span>, <span class="at">dotsize=</span><span class="fl">0.65</span>) <span class="sc">+</span></span>
<span id="cb213-3"><a href="basic-statistical-tests.html#cb213-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha=</span><span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb213-4"><a href="basic-statistical-tests.html#cb213-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&#39;Continent&#39;</span>, <span class="at">y=</span><span class="st">&#39;Life expectancy (yrs)&#39;</span>)</span></code></pre></div>
<pre><code>## `stat_bindot()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-86-1.png" width="672" /></p>
<p>Here we want to run a two sample t-test. Before we do that, we’ll need to check if the 2 samples have the same variance. Recall that different t-tests assume different variances:</p>
<ul>
<li>If you assume equal variance, you would use Student’s t-test.</li>
<li>If variances are unequal, use Welch’s t-test.</li>
</ul>
<p>A good rule of thumb is if the larger standard deviation (SD) divded by the smaller SD is less than 2 (SD(larger)/SD(smaller) &lt; 2), then you can assume equal variance. Alternatively, you can test for equal variances:</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="basic-statistical-tests.html#cb215-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)  <span class="co"># for Levene&#39;s test</span></span>
<span id="cb215-2"><a href="basic-statistical-tests.html#cb215-2" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(<span class="at">y =</span> As.Af<span class="sc">$</span>lifeExp, <span class="at">group =</span> As.Af<span class="sc">$</span>continent)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value    Pr(&gt;F)    
## group  1  12.514 0.0006644 ***
##       83                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Since <span class="math inline">\(p = 0.0006644 &lt; 0.05\)</span>, the two samples have significantly different variances. Indeed, the width of the boxplots in the figure above suggested this difference.</p>
<p>Because we have different variances, we need to use Welch’s t-test. By default, <code>t.test()</code> assumes unequal variance. If this wasn’t the case, we would add an additional argument called <code>var.equal = FALSE</code> to <code>t.test()</code>.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="basic-statistical-tests.html#cb217-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(lifeExp <span class="sc">~</span> continent, As.Af, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  lifeExp by continent
## t = -4.0599, df = 44.637, p-value = 0.0001952
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -10.741084  -3.616704
## sample estimates:
## mean in group Africa   mean in group Asia 
##             39.13550             46.31439</code></pre>
<button class="collapsible">
Mann-Whitney U test
</button>
<div class="collapse_content">
<p>The non-parametric test equivalent to the two sample t-test in this case would be the Mann-Whitney U test.</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="basic-statistical-tests.html#cb219-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(lifeExp <span class="sc">~</span> continent, As.Af)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  lifeExp by continent
## W = 443, p-value = 0.0001857
## alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<div id="example-3-paired-t-test" class="section level3" number="10.1.3">
<h3><span class="header-section-number">10.1.3</span> Example 3: Paired t-test</h3>
<p>Next, let’s take a look at life expectancy in 2007:</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="basic-statistical-tests.html#cb221-1" aria-hidden="true" tabindex="-1"></a>gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb221-2"><a href="basic-statistical-tests.html#cb221-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2007</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb221-3"><a href="basic-statistical-tests.html#cb221-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(continent) <span class="sc">%&gt;%</span></span>
<span id="cb221-4"><a href="basic-statistical-tests.html#cb221-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">meanlife =</span> <span class="fu">mean</span>(lifeExp))</span></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##   continent meanlife
##   &lt;fct&gt;        &lt;dbl&gt;
## 1 Africa        54.8
## 2 Americas      73.6
## 3 Asia          70.7
## 4 Europe        77.6
## 5 Oceania       80.7</code></pre>
<p>Has the life expectancy in Africa changed to that in 1952? We can answer this question with a two sample t-test. This time, we would like to match the countries.</p>
<p>First, let’s generate a long data frame.</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="basic-statistical-tests.html#cb223-1" aria-hidden="true" tabindex="-1"></a>Africa <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span></span>
<span id="cb223-2"><a href="basic-statistical-tests.html#cb223-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(continent<span class="sc">==</span><span class="st">&quot;Africa&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb223-3"><a href="basic-statistical-tests.html#cb223-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(country, year, lifeExp)</span>
<span id="cb223-4"><a href="basic-statistical-tests.html#cb223-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Africa)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   country  year lifeExp
##   &lt;fct&gt;   &lt;int&gt;   &lt;dbl&gt;
## 1 Algeria  1952    43.1
## 2 Algeria  1957    45.7
## 3 Algeria  1962    48.3
## 4 Algeria  1967    51.4
## 5 Algeria  1972    54.5
## 6 Algeria  1977    58.0</code></pre>
<p>Second, let’s look at how the life expectancy changed over the years.</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="basic-statistical-tests.html#cb225-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> Africa, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> lifeExp)) <span class="sc">+</span></span>
<span id="cb225-2"><a href="basic-statistical-tests.html#cb225-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> country)) <span class="sc">+</span></span>
<span id="cb225-3"><a href="basic-statistical-tests.html#cb225-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> country, <span class="at">color=</span>country))</span>
<span id="cb225-4"><a href="basic-statistical-tests.html#cb225-4" aria-hidden="true" tabindex="-1"></a><span class="fu">show</span>(p)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-92-1.png" width="672" /></p>
<p>The change in life expectancy between 1952 and 2007 look interesting. Most of the countries have improved, while a few have decreased life expectancy.</p>
<p>Before testing this observation, let’s reorganize our data into a nice (wide) shape.</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="basic-statistical-tests.html#cb226-1" aria-hidden="true" tabindex="-1"></a>Africa.wide <span class="ot">&lt;-</span> <span class="fu">spread</span>(Africa, year, lifeExp)</span>
<span id="cb226-2"><a href="basic-statistical-tests.html#cb226-2" aria-hidden="true" tabindex="-1"></a>Africa.wide</span></code></pre></div>
<pre><code>## # A tibble: 52 x 13
##    country `1952` `1957` `1962` `1967` `1972` `1977` `1982` `1987` `1992` `1997`
##    &lt;fct&gt;    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1 Algeria   43.1   45.7   48.3   51.4   54.5   58.0   61.4   65.8   67.7   69.2
##  2 Angola    30.0   32.0   34     36.0   37.9   39.5   39.9   39.9   40.6   41.0
##  3 Benin     38.2   40.4   42.6   44.9   47.0   49.2   50.9   52.3   53.9   54.8
##  4 Botswa…   47.6   49.6   51.5   53.3   56.0   59.3   61.5   63.6   62.7   52.6
##  5 Burkin…   32.0   34.9   37.8   40.7   43.6   46.1   48.1   49.6   50.3   50.3
##  6 Burundi   39.0   40.5   42.0   43.5   44.1   45.9   47.5   48.2   44.7   45.3
##  7 Camero…   38.5   40.4   42.6   44.8   47.0   49.4   53.0   55.0   54.3   52.2
##  8 Centra…   35.5   37.5   39.5   41.5   43.5   46.8   48.3   50.5   49.4   46.1
##  9 Chad      38.1   39.9   41.7   43.6   45.6   47.4   49.5   51.1   51.7   51.6
## 10 Comoros   40.7   42.5   44.5   46.5   48.9   50.9   52.9   54.9   57.9   60.7
## # … with 42 more rows, and 2 more variables: 2002 &lt;dbl&gt;, 2007 &lt;dbl&gt;</code></pre>
<p>The wide data frame is to align the data from the same country to the same row, so that they have the same index when we call different columns.</p>
<p>We can now run a paired t-test. Think about what we are testing in the code below.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="basic-statistical-tests.html#cb228-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Africa.wide<span class="sc">$</span><span class="st">&#39;2007&#39;</span>, Africa.wide<span class="sc">$</span><span class="st">&#39;1952&#39;</span>, <span class="at">alternative=</span><span class="st">&quot;two.sided&quot;</span>, <span class="at">paired=</span>T)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  Africa.wide$&quot;2007&quot; and Africa.wide$&quot;1952&quot;
## t = 13.042, df = 51, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  13.25841 18.08267
## sample estimates:
## mean of the differences 
##                15.67054</code></pre>
<p>Note in this process we didn’t check the variance. Is this a problem? Why or why not? Recall that the paired t-test is actually a one sample t-test on paired differences.</p>
<p>Similarly, we could again call <code>wilcox.test</code> to run the paired version.</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="basic-statistical-tests.html#cb230-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(Africa.wide<span class="sc">$</span><span class="st">&#39;2007&#39;</span>, Africa.wide<span class="sc">$</span><span class="st">&#39;1952&#39;</span>, <span class="at">paired=</span>T)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  Africa.wide$&quot;2007&quot; and Africa.wide$&quot;1952&quot;
## V = 1369, p-value = 6.087e-10
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<button class="collapsible">
One-tailed and two-tailed tests
</button>
<div class="collapse_content">
<p>Statistical tests can be either 1-tailed or 2-tailed depending on your question. 1-tailed
tests have 2 possibilities (having a right tail or a left tail) whereas 2-tailed tests have 1 possibility (both right and left tail).</p>
<div class="figure">
<img src="assets/Images/Tailed%20T%20tests.png" alt="" />
<p class="caption">One-tailed vs Two-tailed Tests.</p>
</div>
<p><strong>One-tailed tests:</strong> If you know that life expectancy increases over time, then you would
use a 1-tailed t-test to test if life expectancy is greater in 2005 as compared to 1996.</p>
<p><strong>Two-tailed tests:</strong> Use this if you don’t know how means should look. For example, is
the life expectancy in South Korea equal to the life expectancy in Canada?</p>
<p>If in doubt, use a two-tailed test. This is because significance in a two-tailed test is
“more significant” than that of the one-tailed test.</p>
</div>
</div>
<div id="t-test-assumptions" class="section level3" number="10.1.4">
<h3><span class="header-section-number">10.1.4</span> T-test Assumptions</h3>
<p>Since the t-test relies on a normal-like distribution, it has some assumptions.</p>
<p><strong>1. Independence assumption:</strong> the data values should be independent.
(a) Satisfied if the data are from randomly sampled data.</p>
<p><strong>2. Normal population assumption:</strong> the data follows a normal distribution.
(a) If n &lt; 30, use a histogram to check that the data is unimodal and symmetric.
(b) If n ≥ 30, this assumption is fulfilled by the CLT.</p>
<p><strong>3. 10% condition:</strong> when a sample is drawn without replacement, the sample should
be no more than 10% of the population.
• This is usually assumed to be true.</p>
<p>If any of these conditions are not fulfilled, consider using a non-parametric test
equivalent.</p>
<button class="collapsible">
Example Questions
</button>
<div class="collapse_content">
<p><strong>Question 1:</strong> How long can car crash patients jog before and after
physiotherapy?</p>
<p><strong>Question 2:</strong> Is the mean life expectancy in Argentina different before and
after 1980?</p>
<p>Here is the equation to get the test statistic:
<img src="assets/Images/Test%20Statistic.png" alt="test statistic." /></p>
<p>(don’t worry too much about this)</p>
</div>
</div>
</div>
<div id="chi-squared-test" class="section level2" number="10.2">
<h2><span class="header-section-number">10.2</span> Chi-squared test</h2>
<hr />
<p><strong>Chi-squared test.</strong> A chi-squared test determines if there is a significant difference between expected and observed data.</p>
<hr />
<div id="chi2-test-for-goodness-of-fit" class="section level3" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> <span class="math inline">\(\chi^2\)</span> test for goodness-of-fit</h3>
<p>Let’s analyze the data in Mendel’s original paper: <a href="http://www.mendelweb.org/">Mendel, Gregor. 1866. Versuche über Plflanzenhybriden. Verhandlungen des naturforschenden Vereines in Brünn, Bd. IV für das Jahr
1865, Abhandlungen, 3–47.</a></p>
<button class="collapsible">
Crash course on Mendelian genetics
</button>
<div class="collapse_content">
<p>Let’s (briefly) learn about <a href="https://www.nature.com/scitable/topicpage/gregor-mendel-and-the-principles-of-inheritance-593/">Mendelian genetics</a> regarding dominant and recessive alleles! Recall that crossing two heterozygotes (Aa x Aa) produces offspring with dominant and recessive phenotypes with an expected ratio of 3:1.</p>
<p><span class="math display">\[\begin{array}{c|cc}
  &amp; \mathbf{A} &amp; \mathbf{a} \\
  \hline
  \mathbf{A} &amp; AA &amp; Aa \\
  \mathbf{a} &amp; Aa &amp; aa
\end{array}\]</span></p>
<p>Also recall that a dihybrid cross (AaBb x AaBb) produces offspring of 4 phenotypes with an expected ratio of 9:3:3:1.</p>
<p><span class="math display">\[\begin{array}{c|cccc}
  &amp; \mathbf{AB} &amp; \mathbf{Ab} &amp; \mathbf{aB} &amp; \mathbf{ab} \\
  \hline
  \mathbf{AB} &amp; AABB &amp; AABb &amp; AaBB &amp; AaBb \\
  \mathbf{Ab} &amp; AABb &amp; AAbb &amp; AaBb &amp; Aabb \\
  \mathbf{aB} &amp; AaBb &amp; AaBb &amp; aaBB &amp; aaBb \\
  \mathbf{ab} &amp; AaBb &amp; Aabb &amp; aaBb &amp; aabb
\end{array}\]</span></p>
</div>
<p><br></p>
<p>In his experiment for seed color, the F2 generation produced 6022 yellow, and 2001 green seeds. Thus, the ratio of yellow:green was 3.01:1. This ratio is not the exact theoretical ratio of 3:1. A meaningful question would be this: Is the discrepancy appeared because of random fluctuation, or is the observed ratio significantly different from 3:1?</p>
<p>To examine whether the observed count fits a theoretical ratio, we will use the goodness-of-fit test.</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="basic-statistical-tests.html#cb232-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">6022</span>, <span class="dv">2001</span>),  <span class="co"># the observed data</span></span>
<span id="cb232-2"><a href="basic-statistical-tests.html#cb232-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.75</span>, <span class="fl">0.25</span>))  <span class="co"># the theoretical probability</span></span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  c(6022, 2001)
## X-squared = 0.014999, df = 1, p-value = 0.9025</code></pre>
<p>A p-value of 0.9025 suggested a good match of observed data with the theoretical values. That is, the differences are not significant.</p>
<p>Let’s assume Mendel had observed a 1000 times larger number of seeds, with the same proportion. That is, 6,022,000 yellow and 2,001,000 green. Obviously this ratio is still 3.01:1. Would it still be a good fit for the theoretical value?</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="basic-statistical-tests.html#cb234-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">6022000</span>, <span class="dv">2001000</span>),   <span class="co"># The observed data, 1000 times larger</span></span>
<span id="cb234-2"><a href="basic-statistical-tests.html#cb234-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.75</span>, <span class="fl">0.25</span>))         <span class="co"># The theoretical probability</span></span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  c(6022000, 2001000)
## X-squared = 14.999, df = 1, p-value = 0.0001076</code></pre>
<p>This time, p = 0.0001076, suggesting a significant deviation from the theoretical ratio. As an extension of CLT, when you sample a large enough sample, the ratio of the categories should approach the true value. In other words, <span class="math inline">\(\chi^2\)</span> test should be increasingly sensitive to small deviations when the sample size increases.</p>
</div>
<div id="chi2-test-for-independence" class="section level3" number="10.2.2">
<h3><span class="header-section-number">10.2.2</span> <span class="math inline">\(\chi^2\)</span> test for independence</h3>
<p>In another experiment, Mendel looked at two pairs of phenotypes of the F2 generation of a double-heterozygote. Below is what he saw:</p>
<ul>
<li>315 round and yellow,</li>
<li>101 wrinkled and yellow,</li>
<li>108 round and green,</li>
<li>32 wrinkled and green.</li>
</ul>
<p>Before we examine the 9:3:3:1 ratio, we want to ask if the two loci are independent of each other. That is, will being yellow increase or decrease the chance of being round (and vice versa)?</p>
<p>To run the <span class="math inline">\(\chi^2\)</span> test for independence, we will first need a contingency table. This time we will manually build a data frame for this purpose.</p>
<button class="collapsible">
Contingency tables
</button>
<div class="collapse_content">
<p>Let’s come back to the data of Asia and Africa in 1952. Take a look at the distribution of the life expectancy for all countries in both continents.</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="basic-statistical-tests.html#cb236-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(As.Af)</span></code></pre></div>
<pre><code>##         country      continent       year         lifeExp     
##  Afghanistan: 1   Africa  :52   Min.   :1952   Min.   :28.80  
##  Algeria    : 1   Americas: 0   1st Qu.:1952   1st Qu.:37.00  
##  Angola     : 1   Asia    :33   Median :1952   Median :40.54  
##  Bahrain    : 1   Europe  : 0   Mean   :1952   Mean   :41.92  
##  Bangladesh : 1   Oceania : 0   3rd Qu.:1952   3rd Qu.:45.01  
##  Benin      : 1                 Max.   :1952   Max.   :65.39  
##  (Other)    :79                                               
##       pop              gdpPercap       
##  Min.   :    60011   Min.   :   298.9  
##  1st Qu.:  1022556   1st Qu.:   684.2  
##  Median :  3379468   Median :  1077.3  
##  Mean   : 19211739   Mean   :  2783.3  
##  3rd Qu.:  8550362   3rd Qu.:  1828.2  
##  Max.   :556263527   Max.   :108382.4  
## </code></pre>
<p>Notice that the median of life expectancy is 40.54. That is, half of the countries had life expectancy greater than 40.54, and the other half less than 40.54.</p>
<p>Let’s define a catagorical variable: the countries with life expectancy &gt; 40.54 years are “longer_lived,” and the others are “shorter_lived.”</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="basic-statistical-tests.html#cb238-1" aria-hidden="true" tabindex="-1"></a>As.Af[<span class="st">&quot;long_short&quot;</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb238-2"><a href="basic-statistical-tests.html#cb238-2" aria-hidden="true" tabindex="-1"></a>As.Af<span class="sc">$</span>long_short[As.Af<span class="sc">$</span>lifeExp <span class="sc">&gt;</span> <span class="fl">40.54</span>] <span class="ot">&lt;-</span> <span class="st">&quot;longer_lived&quot;</span></span>
<span id="cb238-3"><a href="basic-statistical-tests.html#cb238-3" aria-hidden="true" tabindex="-1"></a>As.Af<span class="sc">$</span>long_short[<span class="fu">is.na</span>(As.Af<span class="sc">$</span>long_short)] <span class="ot">&lt;-</span> <span class="st">&quot;shorter_lived&quot;</span></span></code></pre></div>
<p>Now let’s see if the longer lived or shorter lived variable is independent of the continent variable. We realize that both variables are categorical. In this case, we will use chi-squared test.</p>
<p>First, we will make a contingency table of the two variables.</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="basic-statistical-tests.html#cb239-1" aria-hidden="true" tabindex="-1"></a>As.Af <span class="ot">&lt;-</span> <span class="fu">droplevels</span>(As.Af)</span>
<span id="cb239-2"><a href="basic-statistical-tests.html#cb239-2" aria-hidden="true" tabindex="-1"></a>cont <span class="ot">&lt;-</span> <span class="fu">table</span>(As.Af<span class="sc">$</span>continent, As.Af<span class="sc">$</span>long_short)</span>
<span id="cb239-3"><a href="basic-statistical-tests.html#cb239-3" aria-hidden="true" tabindex="-1"></a>cont</span></code></pre></div>
<pre><code>##         
##          longer_lived shorter_lived
##   Africa           21            31
##   Asia             22            11</code></pre>
<p>Here, our null hypothesis is that countries <strong>are independent</strong> of the continent it’s a part of. Likewise, our alternative hypothesis is that countries <strong>are dependent</strong> (not independent) of the continent it’s a part of.</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="basic-statistical-tests.html#cb241-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(cont)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  cont
## X-squared = 4.5769, df = 1, p-value = 0.03241</code></pre>
<p>Given that <span class="math inline">\(p &lt; 0.05\)</span>, our null hypothesis that the two variables are independent is rejected. Whether a country is longer lived or shorter lived is dependent on the continent it is located in.</p>
<p>N.B., this is only a comparison between Africa and Asia, and does not hold true for all continents.</p>
</div>
<p><br></p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="basic-statistical-tests.html#cb243-1" aria-hidden="true" tabindex="-1"></a>Mendel2loci <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb243-2"><a href="basic-statistical-tests.html#cb243-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">yellow =</span> <span class="fu">c</span>(<span class="dv">315</span>, <span class="dv">101</span>),</span>
<span id="cb243-3"><a href="basic-statistical-tests.html#cb243-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">green =</span> <span class="fu">c</span>(<span class="dv">108</span>, <span class="dv">32</span>)</span>
<span id="cb243-4"><a href="basic-statistical-tests.html#cb243-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb243-5"><a href="basic-statistical-tests.html#cb243-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb243-6"><a href="basic-statistical-tests.html#cb243-6" aria-hidden="true" tabindex="-1"></a><span class="co"># adding rownames</span></span>
<span id="cb243-7"><a href="basic-statistical-tests.html#cb243-7" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(Mendel2loci) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;round&quot;</span>, <span class="st">&quot;wrinkled&quot;</span>)</span>
<span id="cb243-8"><a href="basic-statistical-tests.html#cb243-8" aria-hidden="true" tabindex="-1"></a><span class="co"># printing the data frame</span></span>
<span id="cb243-9"><a href="basic-statistical-tests.html#cb243-9" aria-hidden="true" tabindex="-1"></a>Mendel2loci</span></code></pre></div>
<pre><code>##          yellow green
## round       315   108
## wrinkled    101    32</code></pre>
<p>Next we will run the <span class="math inline">\(\chi^2\)</span> test. The null hypothesis is that the distribution is independent of the groups.</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="basic-statistical-tests.html#cb245-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(Mendel2loci)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  Mendel2loci
## X-squared = 0.051332, df = 1, p-value = 0.8208</code></pre>
<p>The p-value of 0.8208, so we cannot reject the null hypothesis. Therefore, we should consider the two traits as independent.</p>
<p>Again, we could try to test for its goodness-of-fit. This time we will not need a contingency table.</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="basic-statistical-tests.html#cb247-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">315</span>, <span class="dv">101</span>, <span class="dv">108</span>, <span class="dv">32</span>),</span>
<span id="cb247-2"><a href="basic-statistical-tests.html#cb247-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">p =</span> <span class="fu">c</span>(<span class="dv">9</span><span class="sc">/</span><span class="dv">16</span>, <span class="dv">3</span><span class="sc">/</span><span class="dv">16</span>, <span class="dv">3</span><span class="sc">/</span><span class="dv">16</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">16</span>))</span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  c(315, 101, 108, 32)
## X-squared = 0.47002, df = 3, p-value = 0.9254</code></pre>
<p>Thus, the data fits the 9:3:3:1 ratio well.</p>
</div>
<div id="chi2-test-for-homogeneity" class="section level3" number="10.2.3">
<h3><span class="header-section-number">10.2.3</span> <span class="math inline">\(\chi^2\)</span> test for homogeneity</h3>
<p>The homogeneity test works the same way as an independence test – the only difference lies in the experimentally design.</p>
<ul>
<li>A test for <strong>independence</strong> draws samples from the <em>same population</em>, and look at two or more categorical variables.</li>
<li>A test for <strong>homogeneity</strong> draws sample from <em>2 or more subgroups of the population</em>, and looks at another categorical variable. The subgroup itself serves as a variable.</li>
</ul>
<p>Recall the hypotheses for the test for homogeneity:</p>
<ul>
<li>H<span class="math inline">\(_0\)</span>: the distribution of a categorical response variable is the same in each subgroup.</li>
<li>H<span class="math inline">\(_a\)</span>: the distribution is not the same in each subgroup.</li>
</ul>
<p>Let’s work through a real-life example.</p>
<style>
  div.blue { background-color:#e6f0ff; border-radius: 10px; padding: 20px; }
</style>
<div class="blue">
<p><b style="font-size: 28px;"> Remdesivir and COVID-19 </b></p>
<p>Remdesivir is an antiviral drug previously tested in animal models infected with coronaviruses like SARS and MERS. As of May 2020, remdesivir had temporary approval from the FDA for use in severely ill COVID-19 patients, and it was the subject of numerous ongoing studies.</p>
<p>A randomized controlled trial conducted in China enrolled 236 patients with severe COVID-19 symptoms; 158 were assigned to receive remdesivir and 78 to receive a placebo. In the remdesivir group, 103 patients showed clinical improvement; in the placebo group, 45 patients showed clinical improvement.</p>
<p><a style="font-size: 12px; color: black; text-decoration: none;"> <em> A placebo is a “fake” treatment. That is, placebos do not contain any active substances that affect health. </em> </a></p>
<p><b style="font-size: 20px;"> Reference </b></p>
<p>Wang, Y., Zhang, D., Du, G., Du, R., Zhao, J., Jin, Y., … Wang, C. (2020). Remdesivir in adults with severe COVID-19: a randomised, double-blind, placebo-controlled, multicentre trial. <em>The Lancet</em>. <a href="https://doi.org/10.1016/S0140-6736(20)31022-9" class="uri">https://doi.org/10.1016/S0140-6736(20)31022-9</a></p>
</div>
<p><br></p>
<p>If we consider the treatment and the placebo group as two subgroups of the population, we would expect the ratios of clinical improvement to be different. Let’s do a <span class="math inline">\(\chi^2\)</span> test for homogeneity. We will start with a contingency table.</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="basic-statistical-tests.html#cb249-1" aria-hidden="true" tabindex="-1"></a>rem_cont <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">treatment =</span> <span class="fu">c</span>(<span class="dv">103</span>, <span class="dv">158-103</span>),</span>
<span id="cb249-2"><a href="basic-statistical-tests.html#cb249-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">placebo =</span> <span class="fu">c</span>(<span class="dv">45</span>, <span class="dv">78-45</span>))</span>
<span id="cb249-3"><a href="basic-statistical-tests.html#cb249-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(rem_cont) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;improvement&quot;</span>, <span class="st">&quot;no improvement&quot;</span>)</span>
<span id="cb249-4"><a href="basic-statistical-tests.html#cb249-4" aria-hidden="true" tabindex="-1"></a>rem_cont</span></code></pre></div>
<pre><code>##                treatment placebo
## improvement          103      45
## no improvement        55      33</code></pre>
<p>Next we will run the test. Before we run the test, answer the following questions:</p>
<ul>
<li>What is our null hypothesis?</li>
<li>What is our alternative hypothesis?</li>
</ul>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="basic-statistical-tests.html#cb251-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(rem_cont)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  rem_cont
## X-squared = 0.95518, df = 1, p-value = 0.3284</code></pre>
<p>What does this result mean?</p>
</div>
<div id="chi2-test-assumptions" class="section level3" number="10.2.4">
<h3><span class="header-section-number">10.2.4</span> <span class="math inline">\(\chi^2\)</span> test assumptions</h3>
<p>All statistical tests have assumptions for them to accurately represent the data. Here
are the assumptions you need to fulfill to use the chi-squared test:</p>
<p><strong>1. Counted data condition:</strong> all data must be “counts” for the categorical variable.</p>
<p><strong>2. Independence assumption:</strong> the counts in the cells should be independent of
each other.
(a) Satisfied if the data are from randomly sampled data.</p>
<p><strong>3. Sample size assumption:</strong> we should expect to see at least 5 individuals in each
cell (recall CLT).
(a) If this isn’t satisfied, take your χ2 results with a grain of salt.</p>
<button class="collapsible">
Example Questions
</button>
<div class="collapse_content">
<p><strong>Question 1:</strong> A study was conducted and gave the table below. We notice a trend within the data,
but how do we quantify it? Note that the numbers are counts.
<img src="assets/Images/Chi%20example%20question%20Figure%201.png" alt="Table 1: Contingency table of heart disease and continent. This data is fictional." /></p>
<p>Question: Is the proportion of having heart disease the same for North Americans as
it is for Africans?</p>
<p><strong>Question 2:</strong> Is there evidence that the longevity of an individual is independent of the
continent from which the individual comes from? Let’s define long-lived as those who’s
life expectancy is greater than 40.54 and short-lived as those less than 40.54.
<img src="assets/Images/Chi%20example%20question%20Table%202.png" alt="Table 2: Table of counts from the gapminder dataset." /></p>
</div>
</div>
</div>
<div id="additional-resources" class="section level2" number="10.3">
<h2><span class="header-section-number">10.3</span> Additional resources</h2>
<button class="collapsible">
Fisher’s exact test (OPTIONAL)
</button>
<div class="collapse_content">
<p>If the count in any cell of our contigency table is less than 5, the <span class="math inline">\(\chi^2\)</span> test will not be useful because of its probability distribution assumption. In this case, we will use Fisher’s exact test.</p>
<p><em>The hypotheses of Fisher’s exact same as that of the <span class="math inline">\(\chi^2\)</span> test.</em> Fisher’s exact test can be used for either homogeneity or independence, depending on your experimental design.</p>
<p>Suppose we have a sample 10 times smaller for the Remdesivir trial:</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="basic-statistical-tests.html#cb253-1" aria-hidden="true" tabindex="-1"></a>small_rem <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">treatment =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">16-10</span>),</span>
<span id="cb253-2"><a href="basic-statistical-tests.html#cb253-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">placebo =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">8-4</span>))</span>
<span id="cb253-3"><a href="basic-statistical-tests.html#cb253-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(rem_cont) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;improvement&quot;</span>, <span class="st">&quot;no improvement&quot;</span>)</span>
<span id="cb253-4"><a href="basic-statistical-tests.html#cb253-4" aria-hidden="true" tabindex="-1"></a>small_rem</span></code></pre></div>
<pre><code>##   treatment placebo
## 1        10       4
## 2         6       4</code></pre>
<p>We have many cells with &lt;5 observations. In this case let’s run Fisher’s exact test.</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="basic-statistical-tests.html#cb255-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(small_rem)</span></code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  small_rem
## p-value = 0.6734
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##   0.2140763 12.7643113
## sample estimates:
## odds ratio 
##   1.630755</code></pre>
<p>The p-value is 0.6734. What does this result mean?</p>
<p>The odds ratio is yet another useful measurement you will often see in medical science articles. For the sake of time, I will leave it to you if you wish to <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2938757/">read up</a> on it.</p>
</div>
<p><br></p>
<button class="collapsible">
Comparison of proportions (OPTIONAL)
</button>
<div class="collapse_content">
<p>In the Remdesivir study, the participants were randomly assigned to each group. Thus, the groups can be treated as independent. It is also reasonable to assume independence of patients within each group.</p>
<p>Suppose we have two proportions <span class="math inline">\(\hat{p}_1\)</span> and <span class="math inline">\(\hat{p}_2\)</span>. Then, the normal model can be applied to the difference of the two proportions, <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span>, if the following assumptions are fulfilled:</p>
<ul>
<li>The sampling distribution for each sample proportion is nearly normal.</li>
<li>The samples are independent random samples from the relevant populations and are independent of each other.</li>
</ul>
<p>Each sample proportion approximately follows a normal model when <span class="math inline">\(n_1p_1\)</span>, <span class="math inline">\(n_1(1 - p_1)\)</span>, <span class="math inline">\(n_2p_2\)</span>, and <span class="math inline">\(n_2(1-p_2)\)</span> are all are <span class="math inline">\(\geq 10\)</span>. To check success-failure in the context of a confidence interval, use <span class="math inline">\(\hat{p}_1\)</span> and <span class="math inline">\(\hat{p}_2\)</span>.</p>
<p>The standard error of the difference in sample proportions is
<span class="math display">\[\sqrt{\dfrac{p_1(1-p_1)}{n_1} + \dfrac{p_2(1-p_2)}{n_2}}. \]</span></p>
<p>For hypothesis testing, an estimate of <span class="math inline">\(p\)</span> is used to compute the standard error of <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span>: <span class="math inline">\(\hat{p}\)</span>, the weighted average of the sample proportions <span class="math inline">\(\hat{p}_1\)</span> and <span class="math inline">\(\hat{p}_2\)</span>,
<span class="math display">\[\hat{p} = \dfrac{n_1\hat{p}_1 + n_2\hat{p}_2}{n_1 + n_2} = \dfrac{x_1 + x_2}{n_1 + n_2}. \]</span></p>
<p>To check success-failure in the context of hypothesis testing, check that <span class="math inline">\(\hat{p}n_1\)</span> and <span class="math inline">\(\hat{p}n_2\)</span> are both <span class="math inline">\(\geq 10\)</span>.</p>
<p>In this case, let’s calculate the The pooled proportion <span class="math inline">\(\hat{p}\)</span>:
<span class="math display">\[\hat{p} = \dfrac{x_1 + x_2}{n_1 + n_2} = 0.627\]</span></p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="basic-statistical-tests.html#cb257-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">103</span>, <span class="dv">45</span>)</span>
<span id="cb257-2"><a href="basic-statistical-tests.html#cb257-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">158</span>, <span class="dv">78</span>)</span>
<span id="cb257-3"><a href="basic-statistical-tests.html#cb257-3" aria-hidden="true" tabindex="-1"></a>p.hat.vector <span class="ot">=</span> x<span class="sc">/</span>n</span>
<span id="cb257-4"><a href="basic-statistical-tests.html#cb257-4" aria-hidden="true" tabindex="-1"></a>p.hat.vector</span></code></pre></div>
<pre><code>## [1] 0.6518987 0.5769231</code></pre>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="basic-statistical-tests.html#cb259-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use r as a calculator</span></span>
<span id="cb259-2"><a href="basic-statistical-tests.html#cb259-2" aria-hidden="true" tabindex="-1"></a>p.hat.pooled <span class="ot">=</span> <span class="fu">sum</span>(x)<span class="sc">/</span><span class="fu">sum</span>(n)</span>
<span id="cb259-3"><a href="basic-statistical-tests.html#cb259-3" aria-hidden="true" tabindex="-1"></a>p.hat.pooled</span></code></pre></div>
<pre><code>## [1] 0.6271186</code></pre>
<p>Next we will check the success-failure condition, which is, <span class="math inline">\(\hat{p}n_1\)</span> and <span class="math inline">\(\hat{p}n_2\)</span> are both <span class="math inline">\(\geq 10\)</span>.</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="basic-statistical-tests.html#cb261-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check success-failure</span></span>
<span id="cb261-2"><a href="basic-statistical-tests.html#cb261-2" aria-hidden="true" tabindex="-1"></a>n<span class="sc">*</span>p.hat.pooled</span></code></pre></div>
<pre><code>## [1] 99.08475 48.91525</code></pre>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="basic-statistical-tests.html#cb263-1" aria-hidden="true" tabindex="-1"></a>n<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> p.hat.pooled)</span></code></pre></div>
<pre><code>## [1] 58.91525 29.08475</code></pre>
<p>The success-failure condition is met; the expected number of successes and failures are all larger than 10.</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="basic-statistical-tests.html#cb265-1" aria-hidden="true" tabindex="-1"></a><span class="co"># conduct inference</span></span>
<span id="cb265-2"><a href="basic-statistical-tests.html#cb265-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> x, <span class="at">n =</span> n)</span></code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions with continuity correction
## 
## data:  x out of n
## X-squared = 0.95518, df = 1, p-value = 0.3284
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.06703113  0.21698245
## sample estimates:
##    prop 1    prop 2 
## 0.6518987 0.5769231</code></pre>
<p>In this example, we tested <span class="math inline">\(H_0: p_1 = p_2\)</span> against <span class="math inline">\(H_a: p_1 \neq p_2\)</span> Here,</p>
<ul>
<li><span class="math inline">\(p_1\)</span> represents the population proportion of clinical improvement in COVID-19 patients treated with remdesivir, and</li>
<li><span class="math inline">\(p_2\)</span> represents the population proportion of clinical improvement in COVID-19 patients treated with a placebo.</li>
</ul>
<p>By convention, <span class="math inline">\(\alpha = 0.05\)</span>. The <span class="math inline">\(p\)</span>-value is 0.3284, which is greater than <span class="math inline">\(\alpha\)</span>.</p>
<p>We conclude that there is insufficient evidence to reject the null hypothesis. Although the proportion of patients who experienced clinical improvement about 7% higher in the remdesivir group, this difference is not big enough to show that remdesivir is more effective than a placebo.</p>
</div>
<p><br></p>
<button class="collapsible">
Visualizing data distributions (OPTIONAL)
</button>
<div class="collapse_content">
<p>We’ve barely scratched the surface of <code>dplyr</code> but I want to point out key things you may start to appreciate.</p>
<p>dplyr’s verbs, such as <code>filter()</code> and <code>select()</code>, are what’s called <a href="http://en.wikipedia.org/wiki/Pure_function">pure functions</a>. To quote from Wickham’s <a href="http://adv-r.had.co.nz/Functions.html">Advanced R Programming book</a>:</p>
<blockquote>
<p>The functions that are the easiest to understand and reason about are pure functions: functions that always map the same input to the same output and have no other impact on the workspace. In other words, pure functions have no side effects: they don’t affect the state of the world in any way apart from the value they return.
And finally, the data is <strong>always</strong> the very first argument of every dplyr function.</p>
</blockquote>
<p>Knowing the properties of the normal distribution is essential in understanding the normal distribution. The position of the peak indicates the mean, whereas the spread of the curve indicates the variance.</p>
<p>Although you might not think your data follows a bell curve, let’s take a look at this example for our exercise. Let’s first install a package that helps us create <a href="https://www.data-to-viz.com/graph/ridgeline.html">ridgeline plots</a>.</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="basic-statistical-tests.html#cb267-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;ggridges&quot;</span>)</span></code></pre></div>
<p>Here we will plot the distribution of the life expectancy of African countries in different years. For each year, distributions are sectioned into quartiles. What could you say about the trend over the years? Please discuss both the mean and variance. What does it mean?</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="basic-statistical-tests.html#cb268-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggridges)</span>
<span id="cb268-2"><a href="basic-statistical-tests.html#cb268-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb268-3"><a href="basic-statistical-tests.html#cb268-3" aria-hidden="true" tabindex="-1"></a><span class="co"># getting all rows with Africa as the continent</span></span>
<span id="cb268-4"><a href="basic-statistical-tests.html#cb268-4" aria-hidden="true" tabindex="-1"></a>Africa.all <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span> <span class="fu">filter</span>(continent <span class="sc">==</span> <span class="st">&quot;Africa&quot;</span>, year <span class="sc">&gt;</span> <span class="dv">1990</span>)</span>
<span id="cb268-5"><a href="basic-statistical-tests.html#cb268-5" aria-hidden="true" tabindex="-1"></a><span class="co"># plotting</span></span>
<span id="cb268-6"><a href="basic-statistical-tests.html#cb268-6" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Africa.all, <span class="fu">aes</span>(lifeExp, <span class="fu">as.factor</span>(year), <span class="at">fill=</span><span class="fu">factor</span>(<span class="fu">stat</span>(quantile)))) <span class="sc">+</span></span>
<span id="cb268-7"><a href="basic-statistical-tests.html#cb268-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_density_ridges</span>(<span class="at">quantiles=</span><span class="dv">4</span>,</span>
<span id="cb268-8"><a href="basic-statistical-tests.html#cb268-8" aria-hidden="true" tabindex="-1"></a>                      <span class="at">quantile_lines=</span>T,</span>
<span id="cb268-9"><a href="basic-statistical-tests.html#cb268-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">geom =</span> <span class="st">&#39;density_ridges_gradient&#39;</span>) <span class="sc">+</span></span>
<span id="cb268-10"><a href="basic-statistical-tests.html#cb268-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">name=</span><span class="st">&#39;Quartile&#39;</span>) <span class="sc">+</span></span>
<span id="cb268-11"><a href="basic-statistical-tests.html#cb268-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&#39;Life expectancy (yrs)&#39;</span>, <span class="at">y=</span><span class="st">&#39;Year&#39;</span>) <span class="sc">+</span></span>
<span id="cb268-12"><a href="basic-statistical-tests.html#cb268-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb268-13"><a href="basic-statistical-tests.html#cb268-13" aria-hidden="true" tabindex="-1"></a><span class="fu">show</span>(p)</span></code></pre></div>
<pre><code>## Picking joint bandwidth of 3.6</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-113-1.png" width="672" /></p>
<p>Let’s take a look at the mean and standard deviation to see if your guess is correct.</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="basic-statistical-tests.html#cb270-1" aria-hidden="true" tabindex="-1"></a>Africa.all <span class="sc">%&gt;%</span> </span>
<span id="cb270-2"><a href="basic-statistical-tests.html#cb270-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">c</span>(year, lifeExp)) <span class="sc">%&gt;%</span></span>
<span id="cb270-3"><a href="basic-statistical-tests.html#cb270-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">as.factor</span>(year)) <span class="sc">%&gt;%</span></span>
<span id="cb270-4"><a href="basic-statistical-tests.html#cb270-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_life =</span> <span class="fu">mean</span>(lifeExp), <span class="at">sd_life =</span> <span class="fu">sd</span>(lifeExp))</span></code></pre></div>
<pre><code>## # A tibble: 4 x 3
##   `as.factor(year)` mean_life sd_life
##   &lt;fct&gt;                 &lt;dbl&gt;   &lt;dbl&gt;
## 1 1992                   53.6    9.46
## 2 1997                   53.6    9.10
## 3 2002                   53.3    9.59
## 4 2007                   54.8    9.63</code></pre>
<p>This visualization shows the same information as that in with the density plots, but in a more digestible manner.</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="basic-statistical-tests.html#cb272-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> Africa.all, <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">as.factor</span>(year), <span class="at">y=</span>lifeExp)) <span class="sc">+</span></span>
<span id="cb272-2"><a href="basic-statistical-tests.html#cb272-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_dotplot</span>(<span class="at">binaxis =</span> <span class="st">&#39;y&#39;</span>, <span class="at">stackdir =</span> <span class="st">&#39;center&#39;</span>, <span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb272-3"><a href="basic-statistical-tests.html#cb272-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha=</span><span class="fl">0.3</span>)</span>
<span id="cb272-4"><a href="basic-statistical-tests.html#cb272-4" aria-hidden="true" tabindex="-1"></a><span class="fu">show</span>(p)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-115-1.png" width="672" /></p>
<p>You may want to remove the gray background and decrease dot size. This is as easy as specifying the <code>dotsize</code> parameter and adding <code>theme_classic()</code>. There a lot more themes out there! Check them out <a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">here</a>.</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="basic-statistical-tests.html#cb273-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> Africa.all, <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">as.factor</span>(year), <span class="at">y=</span>lifeExp)) <span class="sc">+</span></span>
<span id="cb273-2"><a href="basic-statistical-tests.html#cb273-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_dotplot</span>(<span class="at">binaxis =</span> <span class="st">&#39;y&#39;</span>, <span class="at">stackdir =</span> <span class="st">&#39;center&#39;</span>, <span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">dotsize =</span> <span class="fl">0.65</span>) <span class="sc">+</span></span>
<span id="cb273-3"><a href="basic-statistical-tests.html#cb273-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha=</span><span class="fl">0.3</span>) <span class="sc">+</span> </span>
<span id="cb273-4"><a href="basic-statistical-tests.html#cb273-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb273-5"><a href="basic-statistical-tests.html#cb273-5" aria-hidden="true" tabindex="-1"></a><span class="fu">show</span>(p)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-116-1.png" width="672" /></p>
<p>While we’re at it, let’s also rename the x- and y-axis. Since we’ve saved the plot already, let’s add a label layer to the plot.</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="basic-statistical-tests.html#cb274-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Year&#39;</span>, <span class="at">y =</span> <span class="st">&#39;Life expectancy (yrs)&#39;</span>)</span>
<span id="cb274-2"><a href="basic-statistical-tests.html#cb274-2" aria-hidden="true" tabindex="-1"></a><span class="fu">show</span>(p)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-117-1.png" width="672" /></p>
<p>Now this figure is publication-ready.</p>
</div>
<script>
iFrameResize({}, ".interactive");
  
var coll = document.getElementsByClassName("collapsible");
for (var i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.maxHeight){
      content.style.maxHeight = null;
      setTimeout(function() {
        content.style.paddingTop = "0";
        content.style.paddingBottom = "0";
      }, 250)
    } else {
      content.style.paddingTop = "15px";
      content.style.paddingBottom = "10px";
      content.style.maxHeight = content.scrollHeight + "px";
    } 
  });
}
</script>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="hypothesis-testing-and-p-values.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="analysis-of-variance.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
